### ISSUE TITLE
"Killing unwanted pod" messages never stop

### ISSUE THREAD

**Issue by fungusakafungus** [cri-o/cri-o#1515]
**Description**

I'm using k8s 1.9.6 and crio 1.9.10 on openstack.
After starting and stopping many pods(for example when running heptio sonobuoy scanner), sometimes I see a flood of messages in kubelet logs in form `Killing unwanted pod "some-pod"`. These messages repeat every two seconds. They appear only on some nodes. The pods mentioned in the message are no longer known to k8s api (`kubectl get pod -a` does not show them). The messages disappear when I restart crio. The to-be-killed pods can be seen in the output of `crictl sandboxes` and `crioctl pod list`.

**Steps to reproduce the issue:**
1. Get [reproducer.yaml](https://github.com/kubernetes-incubator/cri-o/files/1889921/reproducer.yaml.txt) or
```
cat > reproducer.yml <<EOF
---
kind: Namespace
apiVersion: v1
metadata:
  name: reproducer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reproducer
  namespace: reproducer
spec:
  replicas: 100
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: reproducer
    spec:
      volumes:
        - name: reproducer
          emptyDir: {}
      containers:
      - name: reproducer
        image: busybox
        args:
          - sleep
          - "3600"
        volumeMounts:
          - name: reproducer
            mountPath: /reproducer
EOF
```
2. Run `kubectl apply -f reproducer.yaml ; sleep 20; kubectl -n reproducer delete pod --all; sleep 20; kubectl delete ns reproducer` to create 100 pods, delete them all so they get recreated, and delete the namespace.
3. Wait about ten minutes for namespace to get deleted and for cluster to settle.

**Describe the results you received:**
Messages like `Killing unwanted pod "reproducer-5f6c5486f8-5xcr2"` are repeatedly appearing in kubelet logs on some worker nodes.

**Describe the results you expected:**
Messages regarding deleted namespace/pods cease to appear in logs.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have five worker nodes. Three of them exposed that problem after running the reproducer.
Nodes that expose the problem are different from run to tun.

Problem is mitigated by restarting crio.

I'm also not sure, whether emptyDir volumes have anything to do with this.

**Output of `crio --version`:**
```
crio version 1.9.10
commit: "87237324485137e0f439c3011999401186b62874"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on openstack, deployed with homegrown ansible scripts.

```
root@hardway-worker-1:~# systemctl cat crio
# /etc/systemd/system/crio.service
[Unit]
Description=CRI-O daemon
Documentation=https://github.com/kubernetes-incubator/cri-o

[Service]
ExecStart=/usr/local/bin/crio
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
```

```
root@hardway-worker-1:~# cat /etc/crio/crio.conf | grep -v '^#' | grep -v '^$'
[crio]
root = "/var/lib/containers/storage"
runroot = "/var/run/containers/storage"
storage_driver = "overlay2"
storage_option = [
]
[crio.api]
listen = "/var/run/crio.sock"
stream_address = ""
stream_port = "10010"
file_locking = true
[crio.runtime]
runtime = "/usr/local/bin/runc"
runtime_untrusted_workload = ""
default_workload_trust = "trusted"
no_pivot = false
conmon = "/usr/local/libexec/crio/conmon"
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]
selinux = false
seccomp_profile = "/etc/crio/seccomp.json"
apparmor_profile = "crio-default"
cgroup_manager = "cgroupfs"
hooks_dir_path = "/usr/share/containers/oci/hooks.d"
default_mounts = [
]
pids_limit = 1024
enable_shared_pid_namespace = false
log_size_max = -1
[crio.image]
default_transport = "docker://"
pause_image = "kubernetes/pause"
pause_command = "/pause"
signature_policy = ""
image_volumes = "mkdir"
insecure_registries = [
	"docker-registry.company.lan",
]
registries = [
	"docker.io",
]
[crio.network]
network_dir = "/etc/cni/net.d/"
plugin_dir = "/opt/cni/bin/"
```

**Comment by fungusakafungus** [comment]
Looks like removing volumes from `reproducer.yml` does not fix it, so here's a smaller `reproducer.yaml`:
```yaml
---
kind: Namespace
apiVersion: v1
metadata:
  name: reproducer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reproducer
  namespace: reproducer
spec:
  replicas: 100
  template:
    metadata:
      labels:
        app: reproducer
    spec:
      containers:
      - name: reproducer
        image: busybox
        args:
          - sleep
          - "3600"
```

**Comment by fungusakafungus** [comment]
Here's what I see when I grep for one of those pods:

```
root@hardway-worker-1:~# journalctl | grep reproducer-7b4fcc479d-nwc2g
Apr 09 13:37:58 hardway-worker-1 kubelet[5769]: I0409 13:37:58.619291    5769 kubelet.go:1851] SyncLoop (ADD, "api"): "reproducer-7b4fcc479d-nwc2g_reproducer(3720aee5-3bfb-11e8-9969-fa163e583850)"
Apr 09 13:37:58 hardway-worker-1 kubelet[5769]: I0409 13:37:58.862627    5769 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-tpfxt" (UniqueName: "kubernetes.io/secret/3720aee5-3bfb-11e8-9969-fa163e583850-default-token-tpfxt") pod "reproducer-7b4fcc479d-nwc2g" (UID: "3720aee5-3bfb-11e8-9969-fa163e583850")
Apr 09 13:37:59 hardway-worker-1 kubelet[5769]: I0409 13:37:59.023034    5769 reconciler.go:262] operationExecutor.MountVolume started for volume "default-token-tpfxt" (UniqueName: "kubernetes.io/secret/3720aee5-3bfb-11e8-9969-fa163e583850-default-token-tpfxt") pod "reproducer-7b4fcc479d-nwc2g" (UID: "3720aee5-3bfb-11e8-9969-fa163e583850")
Apr 09 13:37:59 hardway-worker-1 kubelet[5769]: I0409 13:37:59.696929    5769 operation_generator.go:523] MountVolume.SetUp succeeded for volume "default-token-tpfxt" (UniqueName: "kubernetes.io/secret/3720aee5-3bfb-11e8-9969-fa163e583850-default-token-tpfxt") pod "reproducer-7b4fcc479d-nwc2g" (UID: "3720aee5-3bfb-11e8-9969-fa163e583850")
Apr 09 13:37:59 hardway-worker-1 kubelet[5769]: I0409 13:37:59.817545    5769 kuberuntime_manager.go:385] No sandbox for pod "reproducer-7b4fcc479d-nwc2g_reproducer(3720aee5-3bfb-11e8-9969-fa163e583850)" can be found. Need to start a new one
Apr 09 13:38:00 hardway-worker-1 crio[5767]: time="2018-04-09 13:38:00.544463730Z" level=info msg="Got pod network {Name:reproducer-7b4fcc479d-nwc2g Namespace:reproducer ID:b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44 NetNS:/proc/7870/ns/net PortMappings:[]}"
Apr 09 13:38:00 hardway-worker-1 crio[5767]: time="2018-04-09 13:38:00.610700951Z" level=info msg="Got pod network {Name:reproducer-7b4fcc479d-nwc2g Namespace:reproducer ID:b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44 NetNS:/proc/7870/ns/net PortMappings:[]}"
Apr 09 13:38:00 hardway-worker-1 kubelet[5769]: I0409 13:38:00.644919    5769 kubelet.go:1896] SyncLoop (PLEG): "reproducer-7b4fcc479d-nwc2g_reproducer(3720aee5-3bfb-11e8-9969-fa163e583850)", event: &pleg.PodLifecycleEvent{ID:"3720aee5-3bfb-11e8-9969-fa163e583850", Type:"ContainerStarted", Data:"b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44"}
Apr 09 13:38:09 hardway-worker-1 kubelet[5769]: I0409 13:38:09.802148    5769 kubelet.go:1867] SyncLoop (DELETE, "api"): "reproducer-7b4fcc479d-nwc2g_reproducer(3720aee5-3bfb-11e8-9969-fa163e583850)"
Apr 09 13:38:10 hardway-worker-1 kubelet[5769]: I0409 13:38:10.183241    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
Apr 09 13:38:10 hardway-worker-1 crio[5767]: time="2018-04-09 13:38:10.183913383Z" level=info msg="Got pod network {Name:reproducer-7b4fcc479d-nwc2g Namespace:reproducer ID:b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44 NetNS:/proc/7870/ns/net PortMappings:[]}"
Apr 09 13:38:10 hardway-worker-1 crio[5767]: time="2018-04-09 13:38:10.260943997Z" level=warning msg="failed to destroy network for pod sandbox k8s_reproducer-7b4fcc479d-nwc2g_reproducer_3720aee5-3bfb-11e8-9969-fa163e583850_0(b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44): failed to Statfs "/proc/7870/ns/net": no such file or directory"
Apr 09 13:38:10 hardway-worker-1 kubelet[5769]: E0409 13:38:10.312263    5769 remote_runtime.go:115] StopPodSandbox "b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44" from runtime service failed: rpc error: code = Unknown desc = failed to stop infra container k8s_POD_reproducer-7b4fcc479d-nwc2g_reproducer_3720aee5-3bfb-11e8-9969-fa163e583850_0 in pod sandbox b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44: failed to stop container b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44, `/usr/local/bin/runc kill b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44 TERM` failed: exit status 1
Apr 09 13:38:10 hardway-worker-1 kubelet[5769]: E0409 13:38:10.312460    5769 kubelet_pods.go:1121] Failed killing the pod "reproducer-7b4fcc479d-nwc2g": failed to "KillPodSandbox" for "3720aee5-3bfb-11e8-9969-fa163e583850" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop infra container k8s_POD_reproducer-7b4fcc479d-nwc2g_reproducer_3720aee5-3bfb-11e8-9969-fa163e583850_0 in pod sandbox b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44: failed to stop container b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44, `/usr/local/bin/runc kill b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44 TERM` failed: exit status 1"
Apr 09 13:38:12 hardway-worker-1 kubelet[5769]: I0409 13:38:12.097099    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
Apr 09 13:38:12 hardway-worker-1 crio[5767]: time="2018-04-09 13:38:12.097688537Z" level=info msg="Got pod network {Name:reproducer-7b4fcc479d-nwc2g Namespace:reproducer ID:b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44 NetNS:/proc/7870/ns/net PortMappings:[]}"
Apr 09 13:38:12 hardway-worker-1 crio[5767]: time="2018-04-09 13:38:12.142789587Z" level=warning msg="failed to destroy network for pod sandbox k8s_reproducer-7b4fcc479d-nwc2g_reproducer_3720aee5-3bfb-11e8-9969-fa163e583850_0(b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44): failed to Statfs "/proc/7870/ns/net": no such file or directory"
Apr 09 13:38:21 hardway-worker-1 kubelet[5769]: E0409 13:38:21.034354    5769 pod_workers.go:186] Error syncing pod 3720aee5-3bfb-11e8-9969-fa163e583850 ("reproducer-7b4fcc479d-nwc2g_reproducer(3720aee5-3bfb-11e8-9969-fa163e583850)"), skipping: failed to "StartContainer" for "reproducer" with CreateContainerConfigError: "cannot find volume \"default-token-tpfxt\" to mount into container \"reproducer\""
Apr 09 13:38:42 hardway-worker-1 kubelet[5769]: I0409 13:38:42.189715    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
Apr 09 13:38:42 hardway-worker-1 kubelet[5769]: I0409 13:38:42.261507    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
Apr 09 13:38:42 hardway-worker-1 kubelet[5769]: I0409 13:38:42.283743    5769 kubelet.go:1867] SyncLoop (DELETE, "api"): "reproducer-7b4fcc479d-nwc2g_reproducer(3720aee5-3bfb-11e8-9969-fa163e583850)"
Apr 09 13:38:42 hardway-worker-1 kubelet[5769]: I0409 13:38:42.283853    5769 kubelet.go:1861] SyncLoop (REMOVE, "api"): "reproducer-7b4fcc479d-nwc2g_reproducer(3720aee5-3bfb-11e8-9969-fa163e583850)"
Apr 09 13:38:42 hardway-worker-1 kubelet[5769]: I0409 13:38:42.287299    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
Apr 09 13:39:13 hardway-worker-1 kubelet[5769]: I0409 13:39:13.725769    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
Apr 09 13:39:13 hardway-worker-1 kubelet[5769]: I0409 13:39:13.989751    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
Apr 09 13:40:14 hardway-worker-1 kubelet[5769]: I0409 13:40:14.328003    5769 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-nwc2g"
```

**Comment by runcom** [comment]
I can see failures to stop the container by runc

**Comment by fungusakafungus** [comment]
I tried this manually and got
```
root@hardway-worker-1:~# /usr/local/bin/runc kill b33210e3de8469cd446cc3a608c502f64484edf7202e5763c8fb0a09be3eeb44 TERM
container_linux.go:393: signaling init process caused "os: process already finished"
root@hardway-worker-1:~# echo $?
1
```

**Comment by mrunalp** [comment]
This should probably be fixed by #1501.

**Comment by fungusakafungus** [comment]
I'll wait for 1.9.11 and test again then

**Comment by mrunalp** [comment]
I have tagged v1.9.11. The rpms would be available in a bit but you can build from source if you like.

**Comment by rhatdan** [comment]
The package is built in Brew.  rhaos-3.9-rhel-7

**Comment by fungusakafungus** [comment]
Tried with v1.9.11, can't reproduce that bug anymore, looks like it is fixed.

**Comment by fungusakafungus** [comment]
Oops, I've been testing this wrong, on an old (docker) cluster. Sorry!
I still can reproduce the issue with crio v1.9.11:

```
Apr 16 12:12:05 hardway-worker-1 kubelet[31055]: I0416 12:12:05.410464   31055 kubelet.go:1851] SyncLoop (ADD, "api"): "reproducer-7b4fcc479d-2ghfl_reproducer(6084349d-416f-11e8-9969-fa163e583850)"
Apr 16 12:12:05 hardway-worker-1 kubelet[31055]: I0416 12:12:05.566758   31055 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-qrc5l" (UniqueName: "kubernetes.io/secret/6084349d-416f-11e8-9969-fa163e583850-default-token-qrc5l") pod "reproducer-7b4fcc479d-2ghfl" (UID: "6084349d-416f-11e8-9969-fa163e583850")
Apr 16 12:12:05 hardway-worker-1 kubelet[31055]: I0416 12:12:05.723053   31055 reconciler.go:262] operationExecutor.MountVolume started for volume "default-token-qrc5l" (UniqueName: "kubernetes.io/secret/6084349d-416f-11e8-9969-fa163e583850-default-token-qrc5l") pod "reproducer-7b4fcc479d-2ghfl" (UID: "6084349d-416f-11e8-9969-fa163e583850")
Apr 16 12:12:06 hardway-worker-1 kubelet[31055]: I0416 12:12:06.273890   31055 operation_generator.go:523] MountVolume.SetUp succeeded for volume "default-token-qrc5l" (UniqueName: "kubernetes.io/secret/6084349d-416f-11e8-9969-fa163e583850-default-token-qrc5l") pod "reproducer-7b4fcc479d-2ghfl" (UID: "6084349d-416f-11e8-9969-fa163e583850")
Apr 16 12:12:06 hardway-worker-1 kubelet[31055]: I0416 12:12:06.641156   31055 kuberuntime_manager.go:385] No sandbox for pod "reproducer-7b4fcc479d-2ghfl_reproducer(6084349d-416f-11e8-9969-fa163e583850)" can be found. Need to start a new one
Apr 16 12:12:07 hardway-worker-1 crio[30864]: time="2018-04-16 12:12:07.174076130Z" level=info msg="Got pod network {Name:reproducer-7b4fcc479d-2ghfl Namespace:reproducer ID:faf25d8e4dcd6f2b3c6f5f3e92faa03f882761d03c60d4ed2817c2032f66f913 NetNS:/proc/32332/ns/net PortMappings:[]}"
Apr 16 12:12:07 hardway-worker-1 crio[30864]: time="2018-04-16 12:12:07.234627129Z" level=info msg="Got pod network {Name:reproducer-7b4fcc479d-2ghfl Namespace:reproducer ID:faf25d8e4dcd6f2b3c6f5f3e92faa03f882761d03c60d4ed2817c2032f66f913 NetNS:/proc/32332/ns/net PortMappings:[]}"
Apr 16 12:12:08 hardway-worker-1 kubelet[31055]: I0416 12:12:08.248978   31055 kubelet.go:1896] SyncLoop (PLEG): "reproducer-7b4fcc479d-2ghfl_reproducer(6084349d-416f-11e8-9969-fa163e583850)", event: &pleg.PodLifecycleEvent{ID:"6084349d-416f-11e8-9969-fa163e583850", Type:"ContainerStarted", Data:"faf25d8e4dcd6f2b3c6f5f3e92faa03f882761d03c60d4ed2817c2032f66f913"}
Apr 16 12:12:23 hardway-worker-1 kubelet[31055]: I0416 12:12:23.932729   31055 kubelet.go:1867] SyncLoop (DELETE, "api"): "reproducer-7b4fcc479d-2ghfl_reproducer(6084349d-416f-11e8-9969-fa163e583850)"
Apr 16 12:12:40 hardway-worker-1 kubelet[31055]: E0416 12:12:40.458432   31055 pod_workers.go:186] Error syncing pod 6084349d-416f-11e8-9969-fa163e583850 ("reproducer-7b4fcc479d-2ghfl_reproducer(6084349d-416f-11e8-9969-fa163e583850)"), skipping: failed to "StartContainer" for "reproducer" with CreateContainerConfigError: "cannot find volume \"default-token-qrc5l\" to mount into container \"reproducer\""
Apr 16 12:12:54 hardway-worker-1 kubelet[31055]: I0416 12:12:54.405310   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
Apr 16 12:12:54 hardway-worker-1 crio[30864]: time="2018-04-16 12:12:54.410397564Z" level=info msg="Got pod network {Name:reproducer-7b4fcc479d-2ghfl Namespace:reproducer ID:faf25d8e4dcd6f2b3c6f5f3e92faa03f882761d03c60d4ed2817c2032f66f913 NetNS:/proc/32332/ns/net PortMappings:[]}"
Apr 16 12:12:54 hardway-worker-1 crio[30864]: time="2018-04-16 12:12:54.507387356Z" level=warning msg="failed to destroy network for pod sandbox k8s_reproducer-7b4fcc479d-2ghfl_reproducer_6084349d-416f-11e8-9969-fa163e583850_0(faf25d8e4dcd6f2b3c6f5f3e92faa03f882761d03c60d4ed2817c2032f66f913): failed to Statfs "/proc/32332/ns/net": no such file or directory"
Apr 16 12:13:24 hardway-worker-1 kubelet[31055]: I0416 12:13:24.581243   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
Apr 16 12:13:24 hardway-worker-1 kubelet[31055]: I0416 12:13:24.626440   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
Apr 16 12:13:55 hardway-worker-1 kubelet[31055]: I0416 12:13:55.065211   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
Apr 16 12:13:55 hardway-worker-1 kubelet[31055]: I0416 12:13:55.131353   31055 kubelet.go:1867] SyncLoop (DELETE, "api"): "reproducer-7b4fcc479d-2ghfl_reproducer(6084349d-416f-11e8-9969-fa163e583850)"
Apr 16 12:13:55 hardway-worker-1 kubelet[31055]: I0416 12:13:55.132076   31055 kubelet.go:1861] SyncLoop (REMOVE, "api"): "reproducer-7b4fcc479d-2ghfl_reproducer(6084349d-416f-11e8-9969-fa163e583850)"
Apr 16 12:13:55 hardway-worker-1 kubelet[31055]: I0416 12:13:55.133335   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
Apr 16 12:13:56 hardway-worker-1 kubelet[31055]: I0416 12:13:56.726713   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
Apr 16 12:14:27 hardway-worker-1 kubelet[31055]: I0416 12:14:27.089949   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
Apr 16 12:14:27 hardway-worker-1 kubelet[31055]: I0416 12:14:27.435679   31055 kubelet_pods.go:1118] Killing unwanted pod "reproducer-7b4fcc479d-2ghfl"
```

**Comment by rhatdan** [comment]
@fungusakafungus Are you still seeing this with latest cri-o?

**Comment by fungusakafungus** [comment]
Sorry, not using cri-o anymore, so not seeing it anymore :)

**Comment by abhishek-ramanujan** [comment]
Since the author has abandoned the issue and the issue was closed without resolution, reviving the issue.

This is still an issue with cri-o version 1.19
