### ISSUE TITLE
Sandbox already exists after node reboot

### ISSUE THREAD

**Issue by jnummelin** [cri-o/cri-o#1742]
**Description**

**Steps to reproduce the issue:**
1. Setup Kube with CRI-O 1.11.1
2. Reboot a node
3. 

**Describe the results you received:**

After reboot no pods can be created. Kubelet always gets an error from crio:
```
Aug 16 10:49:35 pharos-worker-0 kubelet[1503]: W0816 10:49:35.119467    1503 status_manager.go:482] Failed to get status for pod "pharos-proxy-pharos-worker-0_kube-system(f2ed2b7c8d4f0463b262f46b7a3856b9)": Get https://localhost:6443/api/v1/namespaces/kube-system/pods/pharos-proxy-pharos-worker-0: dial tcp 127.0.0.1:6443: connect: connection refused
Aug 16 10:49:35 pharos-worker-0 kubelet[1503]: E0816 10:49:35.134458    1503 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = pod sandbox with name "k8s_pharos-proxy-pharos-worker-0_kube-system_f2ed2b7c8d4f0463b262f46b7a3856b9_0" already exists
Aug 16 10:49:35 pharos-worker-0 kubelet[1503]: E0816 10:49:35.134538    1503 kuberuntime_sandbox.go:56] CreatePodSandbox for pod "pharos-proxy-pharos-worker-0_kube-system(f2ed2b7c8d4f0463b262f46b7a3856b9)" failed: rpc error: code = Unknown desc = pod sandbox with name "k8s_pharos-proxy-pharos-worker-0_kube-system_f2ed2b7c8d4f0463b262f46b7a3856b9_0" already exists
Aug 16 10:49:35 pharos-worker-0 kubelet[1503]: E0816 10:49:35.134552    1503 kuberuntime_manager.go:646] createPodSandbox for pod "pharos-proxy-pharos-worker-0_kube-system(f2ed2b7c8d4f0463b262f46b7a3856b9)" failed: rpc error: code = Unknown desc = pod sandbox with name "k8s_pharos-proxy-pharos-worker-0_kube-system_f2ed2b7c8d4f0463b262f46b7a3856b9_0" already exists
```

CRI-O logs also show some errors after reboot:
```
-- Logs begin at Thu 2018-08-16 10:49:11 UTC, end at Thu 2018-08-16 11:59:52 UTC. --
Aug 16 10:49:14 pharos-worker-0 systemd[1]: Starting Open Container Initiative Daemon...
Aug 16 10:49:14 pharos-worker-0 sysctl[1490]: net.ipv4.ip_forward = 1
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.809774896Z" level=info msg="[graphdriver] using prior storage driver: overlay"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.819928928Z" level=info msg="CNI network pharos (type=weave-net) is used from /etc/cni/net.d/00-pharos.conflist"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.819951403Z" level=info msg="Initial CNI setting succeeded"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.874817377Z" level=warning msg="could not restore sandbox 563be37a1089ed4e57ccb41fcad923262514189111aee88fd4b03e82af22c3b9 container 563be37a1089ed4e57ccb41fcad923262514189111aee88fd4b03e82af22c3b9: open /var/run/containers/storage/overlay-containers/563be37a1089ed4e57ccb41fcad923262514189111aee88fd4b03e82af22c3b9/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.874882490Z" level=warning msg="could not restore sandbox 45f7b1b7037e9f0c89de29bae6e9851ac4ce94aff11e7ff65ca2f998445d6439 container 45f7b1b7037e9f0c89de29bae6e9851ac4ce94aff11e7ff65ca2f998445d6439: open /var/run/containers/storage/overlay-containers/45f7b1b7037e9f0c89de29bae6e9851ac4ce94aff11e7ff65ca2f998445d6439/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875014642Z" level=warning msg="could not restore sandbox ab131c0e092e9e8347b56910f612bf50b89c6ead0c90bbec09ee95f076f461d2 container ab131c0e092e9e8347b56910f612bf50b89c6ead0c90bbec09ee95f076f461d2: open /var/run/containers/storage/overlay-containers/ab131c0e092e9e8347b56910f612bf50b89c6ead0c90bbec09ee95f076f461d2/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875069151Z" level=warning msg="could not restore sandbox 5a87873e9591cc308c4cad490469f8ddcf54fc71b85d64056c1f873d75f59e58 container 5a87873e9591cc308c4cad490469f8ddcf54fc71b85d64056c1f873d75f59e58: open /var/run/containers/storage/overlay-containers/5a87873e9591cc308c4cad490469f8ddcf54fc71b85d64056c1f873d75f59e58/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875107871Z" level=warning msg="could not restore container d22575619707850de9fc1be3afb2ebf4a21980a82a8c139daf30a3b3cfc90a50: open /var/run/containers/storage/overlay-containers/d22575619707850de9fc1be3afb2ebf4a21980a82a8c139daf30a3b3cfc90a50/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875221658Z" level=warning msg="could not restore container 50255cb7b734aa10719fcc0712e5e6e65d3bc8bbe5b8e4e637304a431c483645: open /var/run/containers/storage/overlay-containers/50255cb7b734aa10719fcc0712e5e6e65d3bc8bbe5b8e4e637304a431c483645/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875336372Z" level=warning msg="could not restore container fb3d0ea85b6ac97a23becefab610a76108be1086c551efb576c9dd468924b706: open /var/run/containers/storage/overlay-containers/fb3d0ea85b6ac97a23becefab610a76108be1086c551efb576c9dd468924b706/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875433800Z" level=warning msg="could not restore container a942ea6b2b97c4528e4d43d8fa9278776e3fc2672838dea16c09678b790f9d6f: open /var/run/containers/storage/overlay-containers/a942ea6b2b97c4528e4d43d8fa9278776e3fc2672838dea16c09678b790f9d6f/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875471488Z" level=warning msg="could not restore container 6bff7a83a7d6d91bbc4fb745ff3649eb1f13ec189dbe387ca8cfda0d30b58a4e: open /var/run/containers/storage/overlay-containers/6bff7a83a7d6d91bbc4fb745ff3649eb1f13ec189dbe387ca8cfda0d30b58a4e/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875559127Z" level=warning msg="could not restore container 65c92394ff515dd385a83874c0faf86450c99ed8c5bd16d36ef9e38e95abfd7c: open /var/run/containers/storage/overlay-containers/65c92394ff515dd385a83874c0faf86450c99ed8c5bd16d36ef9e38e95abfd7c/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 crio[1507]: time="2018-08-16 10:49:14.875684359Z" level=warning msg="could not restore container ab2aefc0221c18153bc1ada4096baee42b918d8fe554b68e746a23731d938e2f: open /var/run/containers/storage/overlay-containers/ab2aefc0221c18153bc1ada4096baee42b918d8fe554b68e746a23731d938e2f/userdata/config.json: no such file or directory"
Aug 16 10:49:14 pharos-worker-0 systemd[1]: Started Open Container Initiative Daemon.
```

In this case the pod to be created/started was running fine before reboot. It's a static pod in `/etc/kubernetes/manifest/...`

We've tried many variations in the shutdown process, but cannot seem to get crio to startup properly after reboot.

The only way to "recover" seems to be with:
```
systemctl stop crio
rm -rf /var/lib/containers
rm -rf /var/run/containers
systemctl start crio
```

**Describe the results you expected:**

Kubelet & CRI-O to be able to start/create needed pods after reboot.

**Additional information you deem important (e.g. issue happens only occasionally):**

Based on our testing, reboots seem to work properly with 1.11.0 release

**Output of `crio --version`:**

```
root@pharos-worker-0:~# crio --version
crio version 1.11.1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested on DO with Ubuntu Xenial, Ubuntu Bionic & CentOS 7 with the same results.

**Comment by mrunalp** [comment]
#1744 would probably fix this for you.

**Comment by mrunalp** [comment]
We will port it to release-1.11 branch and cut a new release.

**Comment by jnummelin** [comment]
@mrunalp thanks for speedy turn-around time :)

**Comment by mrunalp** [comment]
@jnummelin Sure :) Can you verify that 1.11.2 fixes the issue for you? If so, then we can close this.

**Comment by jnummelin** [comment]
@mrunalp 1.11.2 confirmed to fix the reboot issue.

**Comment by mythi** [comment]
> That repeats a lot.

I saw this too. It's actually pretty bad because it fires new /pause containers all the time and eventually your worker is on its knees (see ```ps ax```).

**Comment by mythi** [comment]
> So far I haven't been able to figure out a workaround how to safely migrate from 1.11.1 --> 1.11.2.

One thing to try is you copy the relevant pieces in ```/var/run/container``` under ```/var/lib/container``` before reboot.

**Comment by runcom** [comment]
> One thing to try is you copy the relevant pieces in /var/run/container under /var/lib/container before reboot.

that's probably meaning that we're not storing to disk something important during an on/off phase of the system :thinking:

**Comment by mjudeikis** [comment]
we observed something similar, but this was fresh start of the node. mean none of the containers were running before, and nothing started apart of docker and cri-o processes (OCP 3.11).
```
Nov 09 10:11:43 master-000002 atomic-openshift-node[6003]: E1109 10:11:43.477794    6003 pod_workers.go:186] Error syncing pod 64da4761f4f96eac4d37d59897c078e8 ("master-api-master-000002_kube-system(64da4761f4f9
6eac4d37d59897c078e8)"), skipping: failed to "CreatePodSandbox" for "master-api-master-000002_kube-system(64da4761f4f96eac4d37d59897c078e8)" with CreatePodSandboxError: "CreatePodSandbox for pod \"master-api-mas
ter-000002_kube-system(64da4761f4f96eac4d37d59897c078e8)\" failed: rpc error: code = Unknown desc = pod sandbox with name \"k8s_master-api-master-000002_kube-system_64da4761f4f96eac4d37d59897c078e8_0\" already e
xists"                                                                                                                                                                                                             
Nov 09 10:11:43 master-000002 atomic-openshift-node[6003]: I1109 10:11:43.477820    6003 server.go:470] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"master-api-master-000002", UID:"64da476
1f4f96eac4d37d59897c078e8", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedCreatePodSandBox' Failed create pod sandbox: rpc error: code = Unknown desc = pod sandbox with name
 "k8s_master-api-master-000002_kube-system_64da4761f4f96eac4d37d59897c078e8_0" already exists 
```

Somehow it got this on the api server static pod statup :/

**Comment by runcom** [comment]
@jnummelin do you still have issues with upgrading from 1.11.1 to 1.11.2? Maybe this commit which went into 1.11.2 should help https://github.com/kubernetes-sigs/cri-o/commit/2b3add5685469ecd67dbd7c67496230091ea8490

@mjudeikis are you using CRI-O >= 1.11.2?

**Comment by jnummelin** [comment]
@runcom I think I did try it, cannot remember for sure. :) We're running and shipping with Pharos 1.11.6 already

**Comment by cyphar** [comment]
We have seen this quite a lot recently with the `1.9.x` -> `1.10.x` upgrade. After looking at this for a while it definitely looks like there's something wrong with the on-disk state and some aspect of cri-o **really** doesn't like it. I couldn't find any logs that explained why `cri-o` was continually trying to start new pods but not cleaning up after the failure.

From what I've seen, the problem manifests with DaemonSets (if you have pods defined in a manifest and started on-boot they seem to start fine) but that might just be because our upgrade testing does a `kubectl drain` (which won't kill DaemonSets).

It should be noted that the way the Ansible folks worked around this is to nuke `/var/lib/containers` from orbit.

**Comment by pohly** [comment]
I'm also seeing this with cri-o 1.11.6.

In my case, I am running a cluster on QEMU virtual machines and, while everything is running, kill the QEMU processes with SIGKILL. That's the same as a sudden powerloss of the machine. My expectation is that a cluster should survive that. Is that perhaps too optimistic?

**Comment by cyphar** [comment]
> My expectation is that a cluster should survive that. Is that perhaps too optimistic?

I would argue that it should definitely survive this. One of the primary goals of cri-o was to have a container management process that could consistently survive death -- something that Docker will always struggle with.

**Comment by pohly** [comment]
Aleksa Sarai <notifications@github.com> writes:

>> My expectation is that a cluster should survive that. Is that perhaps too optimistic?
>
> I would argue that it should definitely survive this. One of the
> primary goals of cri-o was to have a container management process that
> could consistently survive death -- something that Docker will always
> struggle with.

Thanks for the confirmation. Then this bug needs to remain open, because
right now it doesn't seem to be working. FWIW, Docker worked fine for me
in the same situation (same OS = Clear Linux, same VM setup, hard poweroff).

**Comment by jasonbrooks** [comment]
I'm seeing this with cri-o-1.12.0-12.dev.gitc4f232a.fc29.x86_64 -- it's got to be able to survive an unexpected reboot, I'd say.

**Comment by mrunalp** [comment]
We fixed this in all the branches recently.

**Comment by mrunalp** [comment]
I will cut new releases for it.

**Comment by haircommander** [comment]
Closing per @mrunalp 's comments above, please reopen if you disagree..

**Comment by 0x4139** [comment]
Still reproducing on :
`
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.14.6
RuntimeApiVersion:  v1alpha1
`
