### ISSUE TITLE
Index out of bounds access with invalid `selinuxLabel`

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#1987]
If I call the function `LoadSandbox()` with a container manifest which contains a wrong `selinuxLabel` like 
```json
"process": {
	"selinuxLabel": "wrong"
}
```
 the result will be an out of bounds access. In `vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go:403`.

The main issue is the call to `label.DupSecOpt()`
https://github.com/kubernetes-sigs/cri-o/blob/95ad21041c8a9f337673f97ecca7709daca8b8b2/lib/container_server.go#L356

which builds up the following call stack:
```shell
  Test Panicked
  runtime error: index out of range
  /usr/lib64/go/1.11/src/runtime/panic.go:513

  Full Stack Trace
        /usr/lib64/go/1.11/src/runtime/panic.go:513 +0x1b9
  github.com/kubernetes-sigs/cri-o/vendor/github.com/opencontainers/selinux/go-selinux.NewContext(0xc0000c5198, 0x5, 0x16)
        vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go:403 +0x2b0
  github.com/kubernetes-sigs/cri-o/vendor/github.com/opencontainers/selinux/go-selinux.DupSecOpt(0xc0000c5198, 0x5, 0x0, 0x0, 0xc000376aa0)
        vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go:710 +0x42
  github.com/kubernetes-sigs/cri-o/vendor/github.com/opencontainers/selinux/go-selinux/label.DupSecOpt(0xc0000c5198, 0x5, 0x8, 0x176ac40, 0xc0003b2840)
        vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go:189 +0x35
  github.com/kubernetes-sigs/cri-o/lib.(*ContainerServer).LoadSandbox(0xc000376460, 0x181c6ac, 0x2, 0x0, 0x0)
        lib/container_server.go:359 +0x4a8
```
If we track down the stack we can see that the out of bounds access happens in L403 here:
https://github.com/kubernetes-sigs/cri-o/blob/95ad21041c8a9f337673f97ecca7709daca8b8b2/vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go#L396-L410

I did not create a PR yet since I wanted to discuss with you how to address this issue: In opencontainers/selinux or cri-o? My suggestion would be to fix it directly in selinux-go.

**Comment by rhatdan** [comment]
I think we need to change the selinux DupSecOpt to return errors.

**Comment by umohnani8** [comment]
@rhatdan this is fixed and can be closed right?

**Comment by rhatdan** [comment]
Yes the updated selinux-go package should handle this.

**Comment by rhatdan** [comment]
@saschagrunert @mrunalp Please close.  I don't have the power.

**Comment by saschagrunert** [comment]
@rhatdan I am sorry I have to reopen this, it is not fixed until the selinux-go changes are not used within cri-o.
