### ISSUE TITLE
CentOS 8 Installation: invalid conmon path: stat /usr/libexec/crio/conmon: no such file or directory

### ISSUE THREAD

**Issue by yfstein** [cri-o/cri-o#3818]
BUG REPORT INFORMATION

**Description**
I have installed CRI-O on CentOS 8 server - after that, i tried to `systemctl enable crio` where i saw its not started. Tried to start it with the result `invalid conmon path: stat /usr/libexec/crio/conmon: no such file or directory`

**Steps to reproduce the issue:**
1. Install CRI-O on CentOS 8 server with steps from README.md

```
modprobe overlay
modprobe br_netfilter

# Set up required sysctl params, these persist across reboots.
cat > /etc/sysctl.d/99-kubernetes-cri.conf <<EOF
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sysctl --system
```

```
sudo dnf -y install 'dnf-command(copr)'
sudo dnf -y copr enable rhcontainerbot/container-selinux
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.18.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/CentOS_8/devel:kubic:libcontainers:stable:cri-o:1.18.repo
sudo dnf -y install cri-o
```

2. Try to start it
3. Error successful reproduced 3 times

**Describe the results you received:**
CRIO not starting after `systemctl start crio`

**Describe the results you expected:**
CRIO starting successful with default configuration

**Additional information you deem important (e.g. issue happens only occasionally):**
Cauz i'm setting up a kubernetes cluster, i'm setting it up on 3 identical machines.

**Output of `crio --version`:**

```
crio version 
Version:       1.18.1
GitCommit:     5cbf694c34f8d1af19eb873e39057663a4830635
GitTreeState:  clean
BuildDate:     2020-05-25T19:01:44Z
GoVersion:     go1.13.4
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Environment are 3 CentOS 8 Cloud Server from Hetzner with just installed kubernetes dependencies and some ssh changes

`sudo find / -name "*crio*"`
```
/var/log/crio
/etc/sysconfig/crio-metrics
/etc/sysconfig/crio-network
/etc/sysconfig/crio
/etc/sysconfig/crio-storage
/etc/crio
/etc/crio/crio.conf
/etc/cni/net.d/100-crio-bridge.conf
/usr/share/fish/completions/crio.fish
/usr/share/fish/completions/crio-status.fish
/usr/share/zsh/site-functions/_crio
/usr/share/zsh/site-functions/_crio-status
/usr/share/oci-umount/oci-umount.d/crio-umount.conf
/usr/share/man/man5/crio.conf.5.gz
/usr/share/man/man5/crio.conf.d.5.gz
/usr/share/man/man8/crio-status.8.gz
/usr/share/man/man8/crio.8.gz
/usr/share/bash-completion/completions/crio-status
/usr/share/bash-completion/completions/crio
/usr/libexec/crio
/usr/lib/systemd/system/crio-shutdown.service
/usr/lib/systemd/system/crio.service
/usr/lib/systemd/system/crio-wipe.service
/usr/bin/crio-status
/usr/bin/crio
```

**Comment by yfstein** [comment]
Duplicate:
https://github.com/cri-o/cri-o/issues/3776

**Comment by haircommander** [comment]
is your problem solved by the information in #3776 then @yfstein ?

**Comment by yfstein** [comment]
I thougt, but there was anything wrong so i started a testserver with fresh centos8 installation. Just done some ssh_config changes - after that tryd to install crio. Here my complete setup from a fresh test system:

```
yum update -y
yum install nano -y
yum install wget -y
nano /etc/ssh/sshd_config

Port 5876
PermitRootLogin no
AuthorizedKeysFile .ssh/authorized_keys
ChallenegeResponseAuthentication no
X11Forwarding no

sudo dnf -y install 'dnf-command(copr)'
sudo dnf -y copr enable rhcontainerbot/container-selinux
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.18.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.18/CentOS_8/devel:kubic:libcontainers:stable:cri-o:1.18.repo
sudo dnf -y install cri-o

systemctl enable now cri-o
```

So i think its isnt solved for now.

**Comment by mhudson-bw** [comment]
try this 
mkdir -p /usr/libexec/crio/conmon
then 
systemctl start crio

seems to have worked on my system where crio was spitting out the same message about no such file or directory

**Comment by haircommander** [comment]
the full fix is to either put `/usr/bin/conmon` in `/usr/libexec/crio/conmon` or set `conmon_path` in crio.conf to `""`. though, this should be fixed in the package itself

**Comment by tekmark** [comment]
the conmon binary need to be linked to the path
```
sudo ln -s $(which conmon) /usr/libexec/crio/conmon
```
then try to start the crio again
```
systemctl start crio
```

**Comment by haircommander** [comment]
I am working on fixing this

**Comment by haircommander** [comment]
This should be resolved at the same time we package 1.18.3

**Comment by haircommander** [comment]
this is resolved in 1.18.3

sorry it took so long, and thanks for the patience everyone
