### ISSUE TITLE
"No CNI configuration file in /etc/cni/net.d/" condition remains after CNI has been configured

### ISSUE THREAD

**Issue by stuartpb** [cri-o/cri-o#4276]
**Description**

After running `kubeadm init` (with any necessary flags like `--pod-network-cidr=10.244.0.0/16`), when I deploy a CNI (such as kube-router, though I believe I've seen this issue happen with Weave Net as well) to my cluster and do a `kubectl get nodes`, all of them come back with a `NotReady` status, even after waiting ten minutes, with conditions like this coming back after running `kubectl describe nodes`:

```
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 16 Oct 2020 14:36:35 -0700   Fri, 16 Oct 2020 14:26:47 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 16 Oct 2020 14:36:35 -0700   Fri, 16 Oct 2020 14:26:47 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 16 Oct 2020 14:36:35 -0700   Fri, 16 Oct 2020 14:26:47 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Fri, 16 Oct 2020 14:36:35 -0700   Fri, 16 Oct 2020 14:26:47 -0700   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/cni/net.d/. Has your network provider started?
```

All the CNI pods (ie `kube-router-*`) are running, and checking `/etc/cni/net.d` confirms there *is* a configuration file (ie. `/etc/cni/net.d/10-kuberouter.conflist`). The condition is resolved after running `systemctl restart crio`, but I shouldn't have to restart CRI-O just to fix this.

**Output of `crio --version`:**

```
crio version 1.19.0
Version:       1.19.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     2020-09-15T00:00:00Z
GoVersion:     go1.13.15
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** This is on OpenSUSE Kubic, in a cluster with both amd64 and arm64 nodes. The master node is on a Raspberry Pi 4B with 4GiB RAM.

**Comment by haircommander** [comment]
what is the contents of /etc/cni/net.d/10-kuberouter.conflist
also, can I have the first 30 or so lines in the cri-o logs?

**Comment by anthr76** [comment]
Facing this issue as well on crio 1.9.0 on Kubic. Cilium is CNI provider. `systemctl restart crio` resolves the issue.

```
master-01:/etc/cni/net.d # cat /etc/cni/net.d/05-cilium.conf
{
  "cniVersion": "0.3.1",
  "name": "cilium",
  "type": "cilium-cni",
  "enable-debug": false
}
```
After cri-o restart
```
Dec 19 15:53:54 master-01.k8s.rabbito.tech systemd[1]: Stopping Container Runtime Interface for OCI (CRI-O)...
Dec 19 15:53:54 master-01.k8s.rabbito.tech systemd[1]: crio.service: Succeeded.
Dec 19 15:53:54 master-01.k8s.rabbito.tech systemd[1]: Stopped Container Runtime Interface for OCI (CRI-O).
Dec 19 15:53:54 master-01.k8s.rabbito.tech systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.349035932Z" level=info msg="Node configuration value for hugetlb cgroup is true"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.349217819Z" level=info msg="Node configuration value for pid cgroup is true"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.349268151Z" level=info msg="Node configuration value for memoryswap cgroup is true"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.364620027Z" level=info msg="Node configuration value for systemd CollectMode is true"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.366442337Z" level=info msg="[graphdriver] using prior storage driver: overlay"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.369840904Z" level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.376748278Z" level=info msg="Conmon does support the --sync option"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.377022775Z" level=info msg="No seccomp profile specified, using the internal default"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.377056182Z" level=info msg="Installing default AppArmor profile: crio-default"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.552551934Z" level=info msg="Found CNI network cilium (type=cilium-cni) at /etc/cni/net.d/05-cilium.conf"
Dec 19 15:53:54 master-01.k8s.rabbito.tech crio[13076]: time="2020-12-19 15:53:54.552653396Z" level=info msg="Update default CNI network name to cilium"
Dec 19 15:53:55 master-01.k8s.rabbito.tech systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
```

Prior to cri-o restart
```
-- Logs begin at Wed 2020-12-09 00:00:00 UTC, end at Sat 2020-12-19 15:59:27 UTC. --
Dec 09 00:00:35 master-01 systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
-- Reboot --
Dec 09 00:00:35 master-01 systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
-- Reboot --
Dec 09 00:00:35 master-01 crio[1571]: time="2020-12-09 00:00:35.917096793Z" level=info msg="Node configuration value for hugetlb cgroup is true"
Dec 09 00:00:35 master-01 crio[1571]: time="2020-12-09 00:00:35.917274626Z" level=info msg="Node configuration value for pid cgroup is true"
Dec 09 00:00:35 master-01 crio[1571]: time="2020-12-09 00:00:35.917350645Z" level=info msg="Node configuration value for memoryswap cgroup is true"
Dec 09 00:00:35 master-01 crio[1571]: time="2020-12-09 00:00:35.932416608Z" level=info msg="Node configuration value for systemd CollectMode is true"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.201099959Z" level=info msg="[graphdriver] using prior storage driver: overlay"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.201879293Z" level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.218848200Z" level=info msg="Conmon does support the --sync option"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.220373293Z" level=info msg="No seccomp profile specified, using the internal default"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.220468533Z" level=info msg="Installing default AppArmor profile: crio-default"
-- Reboot --
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.218326418Z" level=info msg="Node configuration value for hugetlb cgroup is true"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.218501731Z" level=info msg="Node configuration value for pid cgroup is true"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.218564137Z" level=info msg="Node configuration value for memoryswap cgroup is true"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.235692258Z" level=info msg="Node configuration value for systemd CollectMode is true"
-- Reboot --
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.316886367Z" level=info msg="Update default CNI network name to "
Dec 09 00:00:36 master-01 systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
-- Reboot --
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.787135252Z" level=info msg="[graphdriver] using prior storage driver: overlay"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.796429034Z" level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.815542369Z" level=info msg="Conmon does support the --sync option"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.815889568Z" level=info msg="No seccomp profile specified, using the internal default"
Dec 09 00:00:36 master-01 crio[1571]: time="2020-12-09 00:00:36.815941160Z" level=info msg="Installing default AppArmor profile: crio-default"
Dec 09 00:00:37 master-01 crio[1571]: time="2020-12-09 00:00:37.030339974Z" level=info msg="Found CNI network cilium (type=cilium-cni) at /etc/cni/net.d/05-cilium.conf"
Dec 09 00:00:37 master-01 crio[1571]: time="2020-12-09 00:00:37.030438602Z" level=info msg="Update default CNI network name to cilium"
```

What's odd is physically restarting the node doesn't fix this. Just restarting the service.

Snippet from `kubectl describe node`
```
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Sat, 19 Dec 2020 10:46:05 -0500   Sat, 19 Dec 2020 10:46:05 -0500   CiliumIsUp                   Cilium is running on this node
  Ready                False   Sat, 19 Dec 2020 10:56:14 -0500   Sat, 19 Dec 2020 10:37:58 -0500   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/cni/net.d/. Has your network provider started?
```

```
master-01:/etc/cni/net.d # cat /etc/os-release
NAME="openSUSE MicroOS"
# VERSION="20201214"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20201214"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20201214"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo"
```

**Comment by haircommander** [comment]
is there anything else in that plugin directory before the cilium pod comes up? (bridge plugin config, for instance?)

**Comment by anthr76** [comment]
Just tested. Nothing is present

**Comment by haircommander** [comment]
what's the `[crio.network]` section of `crio config`

**Comment by anthr76** [comment]
```
# The crio.network table containers settings pertaining to the management of
# CNI plugins.
[crio.network]

# The default CNI network name to be selected. If not set or "", then
# CRI-O will pick-up the first one found in network_dir.
# cni_default_network = ""

# Path to the directory where CNI configuration files are located.
network_dir = "/etc/cni/net.d/"

# Paths to directories where CNI plugin binaries are located.
plugin_dirs = [
	"/opt/cni/bin/",
	"/usr/libexec/cni/",
]

# A necessary configuration for Prometheus based metrics retrieval
[crio.metrics]

# Globally enable or disable metrics support.
enable_metrics = false

# The port on which the metrics server will listen.
metrics_port = 9090

# Local socket path to bind the metrics server to
metrics_socket = ""
```

Appears to be a sane config

**Comment by sfxworks** [comment]
Hello,

For anyone running into this issue, I hit it when adding a new control plane node. It was solved by adding the config above to my crio config file. Even though `/etc/cni/net.d/` was populated by cilium in my case, it was not being picked up by kubelet. 

```
[root@pfdc-store-2 ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-04-09T16:47:30Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
[root@pfdc-store-2 ~]# crio version
INFO[2021-05-21 22:24:08.522562650-04:00] Starting CRI-O, version: 1.21.0, git: unknown(unknown)
Version:       1.21.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     2021-04-15T09:31:40Z
GoVersion:     go1.16.3
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
[root@pfdc-store-2 ~]# cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**Comment by uablrek** [comment]
I run into this when trying antrea with cri-o and I found an "interesting" work-around (beside re-start cri-o): when `/etc/cni/net.d/10-antrea.conflist`, wait a few seconds then do;
```
touch /etc/cni/net.d/99-dummy.conf
```
and everything start to work :smiley: 

Seems like `cri-o` reads /etc/cni/net.d *once* when it changes and if things doesnt work, for instance because /opt/cni/bin is not populated, it just sits and wait until next change.

**Comment by uablrek** [comment]
My silly work-around start script;
```bash
#! /bin/sh

if test "$1" != "cni-conf-wait"; then
	$0 cni-conf-wait > /dev/null 2>&1 &
	exit 0
fi

while ! test -r /etc/cni/net.d/10-antrea.conflist; do
	sleep 4
done

sleep 4
touch /etc/cni/net.d/99-dummy.conf
```

**Comment by haircommander** [comment]
We currently should be listening for both new files and changed files in the cni config directory. I wonder if the file being updated by the cni plugin is actually changing, and if we're missing a write because it isn't. I can't think of any other reason this may happen other than simply a dropped inotify message...

**Comment by visheyra** [comment]
Hello, adding a 👍  here as I have the same behaviour with kubeadm 1.22.1 / cilium 1.10.6 and cri-o 1.22, As stated a bit above, restarting the the cri-o unit solve the issue.

**Comment by fsedarkalex** [comment]
Same issue here with kubeadm 1.23.4 / CRI-O 1.23 / Flannel on Debian 11

**Comment by parmentelat** [comment]
as far as I can tell, I am seeing this on fedora-35 with cri-o 1.22
it happens deterministically (all the time) and I had to write a surveillance loop that waits for some file to show up in that folder before it `systemctl restart crio`

**Comment by bogdando** [comment]
I have the same ``No CNI configuration file in /etc/cni/net.d/. Has your network provider started? `` error shown in ``crictl info`` on a custom FCOS based rpm-ostree setup (tried cri-o v1.21 and v1.24). I'm trying it with podman bridge CNI plugin though. 

The podman CNI plugin passes manual checks omitting crio, (``NETCONFPATH=/etc/cni/net.d/ CNI_PATH=/usr/libexec/cni cnitool add podman /var/run/netns/testing``).

And there is microshift in a container on top as well, but that's unrelated. The crux is that ``crictl info`` should not show errors in the first place...

**Comment by bogdando** [comment]
I fixed the problem, so please disregard. There was a microshift.conf for CNI with  cni_default_network set to cbr0. Once I remove it, cri-o restarts and properly picks its cni plugin

**Comment by nuno-aj-aniceto** [comment]
Notice: for the ones using ArchLinux or a very vanilla base, check:
https://wiki.archlinux.org/title/CRI-O
As there is a need to update CRI-O configuration to check the cni directories.
This solved my issue.

**Comment by niklarz** [comment]
> Notice: for the ones using ArchLinux or a very vanilla base, check: https://wiki.archlinux.org/title/CRI-O As there is a need to update CRI-O configuration to check the cni directories. This solved my issue.

Thanks, this solved my issue as well!

**Comment by clbx** [comment]
Still an issue

> I run into this when trying antrea with cri-o and I found an "interesting" work-around (beside re-start cri-o): when `/etc/cni/net.d/10-antrea.conflist` appears, wait a few seconds then do;
> 
> ```
> touch /etc/cni/net.d/99-dummy.conf
> ```
> 
> and everything start to work 😃
> 
> Seems like `cri-o` reads /etc/cni/net.d _once_ when it changes and if things doesnt work, for instance because /opt/cni/bin is not populated, it just sits and wait until next change.

 this fixed it for me CRI-O v1.26.1, Kubernetes v1.26.2, Flannel v0.21.3, Debian 11

**Comment by ramgdev** [comment]
I'm running into this with `cri-o 1.21` and `k8s 1.23`. The node is showing this error after it successfully scheduled pods. So far, it seems unpredictable when the node will get into this state. Is there a permanent fix/solution available yet?

**Comment by haircommander** [comment]
this is not yet fixed, though I think I have an idea of the issue. 

In https://github.com/cri-o/ocicni/blob/master/pkg/ocicni/ocicni.go#L148 we monitor the configuration directory, but inotify doesn't give us an option to check for edit events. I am not sure the package we use for this gives us Modify events, so I think it would have to be rewritten to use this

**Comment by haircommander** [comment]
@ramgdev or anyone else: are you able to test this on a newer version of CRI-O? @amarlearning is working on writing a unit test for this behavior in https://github.com/cri-o/ocicni/pull/165 and sees an updated config when the file is changed.

**Comment by alephpt** [comment]
I'm having the same problem on the newest version running in SUSE el.

**Comment by alrf** [comment]
Same issue on FCOS, `cri-o 1.28.2`, `k8s v1.28.7`

**Comment by mrmahi2003** [comment]
hey can you assign this issue to me ?

**Comment by kwilczynski** [comment]
@mrmahi2003, why?

Do you have something to contribute? If so, then feel free to do so. You can open a Pull Request or add your finding here.

**Comment by speedfly1** [comment]
hi all, did someone resolve it?

**Comment by thedarkone-maheshwara** [comment]
help !!!!
Name:               regalfoyer
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=regalfoyer
                    kubernetes.io/os=linux
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/crio/crio.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 06 Mar 2025 14:52:52 +0530
Taints:             node.kubernetes.io/not-ready:NoExecute
                    node.cilium.io/agent-not-ready:NoSchedule
                    node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  regalfoyer
  AcquireTime:     <unset>
  RenewTime:       Thu, 06 Mar 2025 15:36:33 +0530
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 06 Mar 2025 15:35:32 +0530   Thu, 06 Mar 2025 14:52:52 +0530   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 06 Mar 2025 15:35:32 +0530   Thu, 06 Mar 2025 14:52:52 +0530   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 06 Mar 2025 15:35:32 +0530   Thu, 06 Mar 2025 14:52:52 +0530   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Thu, 06 Mar 2025 15:35:32 +0530   Thu, 06 Mar 2025 14:52:52 +0530   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/cni/net.d/. Has your network provider started?

**Comment by thedarkone-maheshwara** [comment]
basically cilium is not creating /etc/cni/net.d/05-cilium.conflist on worker node hence crio is not picking up the file so cilium is unable to deploy no what should I do ?

**Comment by thedarkone-maheshwara** [comment]
> what is the contents of /etc/cni/net.d/10-kuberouter.conflist also, can I have the first 30 or so lines in the cri-o logs?

the dir is empty Maheshvara@RegalFoyer:~$  ls /etc/cni/net.d/05-cilium.conflist
ls: cannot access '/etc/cni/net.d/05-cilium.conflist': No such file or directory
 and logs of crio :  Mar 07 12:59:42 RegalFoyer crio[20666]: time="2025-03-07 12:59:42.508050228+05:30" level=info msg="Registered SIGHUP reload watcher"
Mar 07 12:59:42 RegalFoyer crio[20666]: time="2025-03-07 12:59:42.508389982+05:30" level=info msg="Starting seccomp notifier watcher"
Mar 07 12:59:42 RegalFoyer crio[20666]: time="2025-03-07 12:59:42.508439816+05:30" level=info msg="Serving metrics on :9537 via HTTP"
Mar 07 12:59:42 RegalFoyer crio[20666]: time="2025-03-07 12:59:42.508445242+05:30" level=info msg="Create NRI interface"
Mar 07 12:59:42 RegalFoyer crio[20666]: time="2025-03-07 12:59:42.508495038+05:30" level=info msg="NRI interface is disabled in the configuration."
Mar 07 12:59:42 RegalFoyer systemd[1]: Started crio.service - Container Runtime Interface for OCI (CRI-O).
Mar 07 13:00:04 RegalFoyer crio[20666]: time="2025-03-07 13:00:04.563443050+05:30" level=info msg="Stopping pod sandbox: a59945b16f8402f4b60272d645010fad6fb3b23743c6da36a7a832e62004d674" id=d4c12c89-0541-4ebd-9f2a-32f56ca3a3c4 name=/runtime.v1.RuntimeService/StopPodSandbox
Mar 07 13:00:04 RegalFoyer crio[20666]: time="2025-03-07 13:00:04.563569444+05:30" level=info msg="Stopped pod sandbox (already stopped): a59945b16f8402f4b60272d645010fad6fb3b23743c6da36a7a832e62004d674" id=d4c12c89-0541-4ebd-9f2a-32f56ca3a3c4 name=/runtime.v1.RuntimeService/StopPodSandbox
Mar 07 13:00:04 RegalFoyer crio[20666]: time="2025-03-07 13:00:04.564738216+05:30" level=info msg="Removing pod sandbox: a59945b16f8402f4b60272d645010fad6fb3b23743c6da36a7a832e62004d674" id=de756cf9-5c94-4863-954d-032e0a88041e name=/runtime.v1.RuntimeService/RemovePodSandbox
Mar 07 13:00:04 RegalFoyer crio[20666]: time="2025-03-07 13:00:04.570234471+05:30" level=info msg="Removed pod sandbox: a59945b16f8402f4b60272d645010fad6fb3b23743c6da36a7a832e62004d674" id=de756cf9-5c94-4863-954d-032e0a88041e name=/runtime.v1.RuntimeService/RemovePodSandbox
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.129573057+05:30" level=info msg="Checking image status: quay.io/cilium/cilium:v1.17.1@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866" id=17fa1470-06d6-4b67-8106-dd2c7065b41e name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.130815876+05:30" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:7560591db8e7313b841a51515cceb8881bc2d740e4d1ec8981916622df707d63,RepoTags:[],RepoDigests:[quay.io/cilium/cilium@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866 quay.io/cilium/cilium@sha256:a731981fef38429551dabdbc347b0f9af66a9f935bcc861117d63bc6681b3ec0],Size_:810194034,Uid:nil,Username:,Spec:&ImageSpec{Image:,Annotations:map[string]string{},UserSpecifiedImage:,},Pinned:false,},Info:map[string]string{},}" id=17fa1470-06d6-4b67-8106-dd2c7065b41e name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.132996469+05:30" level=info msg="Checking image status: quay.io/cilium/cilium:v1.17.1@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866" id=2f17bad7-0af4-472d-9c86-d0e597aa3bc4 name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.133656996+05:30" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:7560591db8e7313b841a51515cceb8881bc2d740e4d1ec8981916622df707d63,RepoTags:[],RepoDigests:[quay.io/cilium/cilium@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866 quay.io/cilium/cilium@sha256:a731981fef38429551dabdbc347b0f9af66a9f935bcc861117d63bc6681b3ec0],Size_:810194034,Uid:nil,Username:,Spec:&ImageSpec{Image:,Annotations:map[string]string{},UserSpecifiedImage:,},Pinned:false,},Info:map[string]string{},}" id=2f17bad7-0af4-472d-9c86-d0e597aa3bc4 name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.135582834+05:30" level=info msg="Creating container: kube-system/cilium-cszjf/config" id=4f069773-aeef-4dcd-a277-deb0adf311d0 name=/runtime.v1.RuntimeService/CreateContainer
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.135794533+05:30" level=warning msg="Allowed annotations are specified for workload [io.containers.trace-syscall]"
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.212694812+05:30" level=info msg="Created container 859429d54cc2d68b2081b30c8f0762271e077042335f5d9a9d23a40806faff25: kube-system/cilium-cszjf/config" id=4f069773-aeef-4dcd-a277-deb0adf311d0 name=/runtime.v1.RuntimeService/CreateContainer
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.213443624+05:30" level=info msg="Starting container: 859429d54cc2d68b2081b30c8f0762271e077042335f5d9a9d23a40806faff25" id=97f7b6cc-9f64-457e-8488-1f39b9eb46f9 name=/runtime.v1.RuntimeService/StartContainer
Mar 07 13:00:41 RegalFoyer crio[20666]: time="2025-03-07 13:00:41.220551067+05:30" level=info msg="Started container" PID=20810 containerID=859429d54cc2d68b2081b30c8f0762271e077042335f5d9a9d23a40806faff25 description=kube-system/cilium-cszjf/config id=97f7b6cc-9f64-457e-8488-1f39b9eb46f9 name=/runtime.v1.RuntimeService/StartContainer sandboxID=f0f6d85ccfc41b4ae5196b35d9588da30ca3aa353cd8c5d59632ce408e00d2a2
Mar 07 13:01:47 RegalFoyer crio[20666]: time="2025-03-07 13:01:47.296283098+05:30" level=info msg="Removing container: 8c86b4f1b475119944bf9b1671b7a78f5ac9860cf8c161fddea22cbe2e4b1b42" id=cdf34aac-3b7a-4ab5-a53f-60393d051d10 name=/runtime.v1.RuntimeService/RemoveContainer
Mar 07 13:01:47 RegalFoyer crio[20666]: time="2025-03-07 13:01:47.296768276+05:30" level=info msg="Removing container: 8c86b4f1b475119944bf9b1671b7a78f5ac9860cf8c161fddea22cbe2e4b1b42" id=1c20e8a8-635b-445e-8dc3-70acaf712905 name=/runtime.v1.RuntimeService/RemoveContainer
Mar 07 13:01:47 RegalFoyer crio[20666]: time="2025-03-07 13:01:47.422238035+05:30" level=info msg="Removed container 8c86b4f1b475119944bf9b1671b7a78f5ac9860cf8c161fddea22cbe2e4b1b42: kube-system/cilium-cszjf/config" id=cdf34aac-3b7a-4ab5-a53f-60393d051d10 name=/runtime.v1.RuntimeService/RemoveContainer
Mar 07 13:01:47 RegalFoyer crio[20666]: time="2025-03-07 13:01:47.423975564+05:30" level=info msg="Container 8c86b4f1b475119944bf9b1671b7a78f5ac9860cf8c161fddea22cbe2e4b1b42 not known, assuming it got already removed" id=1c20e8a8-635b-445e-8dc3-70acaf712905 name=/runtime.v1.RuntimeService/RemoveContainer
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.052979844+05:30" level=info msg="Checking image status: quay.io/cilium/cilium:v1.17.1@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866" id=87f36c0a-fff9-42d1-bae6-4c83dde25c5a name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.053896456+05:30" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:7560591db8e7313b841a51515cceb8881bc2d740e4d1ec8981916622df707d63,RepoTags:[],RepoDigests:[quay.io/cilium/cilium@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866 quay.io/cilium/cilium@sha256:a731981fef38429551dabdbc347b0f9af66a9f935bcc861117d63bc6681b3ec0],Size_:810194034,Uid:nil,Username:,Spec:&ImageSpec{Image:,Annotations:map[string]string{},UserSpecifiedImage:,},Pinned:false,},Info:map[string]string{},}" id=87f36c0a-fff9-42d1-bae6-4c83dde25c5a name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.055661184+05:30" level=info msg="Checking image status: quay.io/cilium/cilium:v1.17.1@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866" id=a45e2e23-285c-4b10-96ea-2e56813ca2d1 name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.056040748+05:30" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:7560591db8e7313b841a51515cceb8881bc2d740e4d1ec8981916622df707d63,RepoTags:[],RepoDigests:[quay.io/cilium/cilium@sha256:8969bfd9c87cbea91e40665f8ebe327268c99d844ca26d7d12165de07f702866 quay.io/cilium/cilium@sha256:a731981fef38429551dabdbc347b0f9af66a9f935bcc861117d63bc6681b3ec0],Size_:810194034,Uid:nil,Username:,Spec:&ImageSpec{Image:,Annotations:map[string]string{},UserSpecifiedImage:,},Pinned:false,},Info:map[string]string{},}" id=a45e2e23-285c-4b10-96ea-2e56813ca2d1 name=/runtime.v1.ImageService/ImageStatus
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.056454986+05:30" level=info msg="Creating container: kube-system/cilium-cszjf/config" id=128f9181-4f85-4d5a-946e-3ee1769171df name=/runtime.v1.RuntimeService/CreateContainer
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.056526197+05:30" level=warning msg="Allowed annotations are specified for workload [io.containers.trace-syscall]"
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.116993560+05:30" level=info msg="Created container 5ff47aaae20f38bc7abd070fc739b747211e6f7279d636080e54350a3ae02c9a: kube-system/cilium-cszjf/config" id=128f9181-4f85-4d5a-946e-3ee1769171df name=/runtime.v1.RuntimeService/CreateContainer
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.117413934+05:30" level=info msg="Starting container: 5ff47aaae20f38bc7abd070fc739b747211e6f7279d636080e54350a3ae02c9a" id=4e7c26db-4d09-401a-9915-e4cf286db1ce name=/runtime.v1.RuntimeService/StartContainer
Mar 07 13:02:02 RegalFoyer crio[20666]: time="2025-03-07 13:02:02.121626409+05:30" level=info msg="Started container" PID=20904 containerID=5ff47aaae20f38bc7abd070fc739b747211e6f7279d636080e54350a3ae02c9a description=kube-system/cilium-cszjf/config id=4e7c26db-4d09-401a-9915-e4cf286db1ce name=/runtime.v1.RuntimeService/StartContainer sandboxID=f0f6d85ccfc41b4ae5196b35d9588da30ca3aa353cd8c5d59632ce408e00d2a2
i restarted crio and kubelet on unhealthy node serval times but it is not helping

**Comment by thedarkone-maheshwara** [comment]
this is my crio config :
Maheshvara@RegalFoyer:~$ sudo cat /etc/crio/crio.conf
# The CRI-O configuration file specifies all of the available configuration
# options and command-line flags for the crio(8) OCI Kubernetes Container Runtime
# daemon, but in a TOML format that can be more easily modified and versioned.
#
# Please refer to crio.conf(5) for details of all configuration options.

# CRI-O supports partial configuration reload during runtime, which can be
# done by sending SIGHUP to the running process. Currently supported options
# are explicitly mentioned with: 'This option supports live configuration
# reload'.

# CRI-O reads its storage defaults from the containers-storage.conf(5) file
# located at /etc/containers/storage.conf. Modify this storage configuration if
# you want to change the system's defaults. If you want to modify storage just
# for CRI-O, you can change the storage configuration options here.
[crio]

# Path to the "root directory". CRI-O stores all of its data, including
# containers images, in this directory.
# root = "/builddir/.local/share/containers/storage"

# Path to the "run directory". CRI-O stores all of its state in this directory.
# runroot = "/tmp/containers-user-1000/containers"

# Storage driver used to manage the storage of images and containers. Please
# refer to containers-storage.conf(5) to see all available storage drivers.
# storage_driver = "overlay"

# List to pass options to the storage driver. Please refer to
# containers-storage.conf(5) to see all available storage options.
# storage_option = [
# ]

# The default log directory where all logs will go unless directly specified by
# the kubelet. The log directory specified must be an absolute directory.
# log_dir = "/var/log/crio/pods"

# Location for CRI-O to lay down the temporary version file.
# It is used to check if crio wipe should wipe containers, which should
# always happen on a node reboot
# version_file = "/var/run/crio/version"

# Location for CRI-O to lay down the persistent version file.
# It is used to check if crio wipe should wipe images, which should
# only happen when CRI-O has been upgraded
# version_file_persist = ""

# InternalWipe is whether CRI-O should wipe containers and images after a reboot when the server starts.
# If set to false, one must use the external command 'crio wipe' to wipe the containers and images in these situations.
# internal_wipe = true

# InternalRepair is whether CRI-O should check if the container and image storage was corrupted after a sudden restart.
# If it was, CRI-O also attempts to repair the storage.
# internal_repair = false

# Location for CRI-O to lay down the clean shutdown file.
# It is used to check whether crio had time to sync before shutting down.
# If not found, crio wipe will clear the storage directory.
# clean_shutdown_file = "/var/lib/crio/clean.shutdown"

# The crio.api table contains settings for the kubelet/gRPC interface.
[crio.api]

# Path to AF_LOCAL socket on which CRI-O will listen.
listen = "/var/run/crio/crio.sock"

# IP address on which the stream server will listen.
# stream_address = "127.0.0.1"

# The port on which the stream server will listen. If the port is set to "0", then
# CRI-O will allocate a random free port number.
# stream_port = "0"

# Enable encrypted TLS transport of the stream server.
# stream_enable_tls = false

# Length of time until open streams terminate due to lack of activity
# stream_idle_timeout = ""

# Path to the x509 certificate file used to serve the encrypted stream. This
# file can change, and CRI-O will automatically pick up the changes within 5
# minutes.
# stream_tls_cert = ""

# Path to the key file used to serve the encrypted stream. This file can
# change and CRI-O will automatically pick up the changes within 5 minutes.
# stream_tls_key = ""

# Path to the x509 CA(s) file used to verify and authenticate client
# communication with the encrypted stream. This file can change and CRI-O will
# automatically pick up the changes within 5 minutes.
# stream_tls_ca = ""

# Maximum grpc send message size in bytes. If not set or <=0, then CRI-O will default to 80 * 1024 * 1024.
# grpc_max_send_msg_size = 83886080

# Maximum grpc receive message size. If not set or <= 0, then CRI-O will default to 80 * 1024 * 1024.
# grpc_max_recv_msg_size = 83886080

# The crio.runtime table contains settings pertaining to the OCI runtime used
# and options for how to set up and manage the OCI runtime.
[crio.runtime]

# A list of ulimits to be set in containers by default, specified as
# "<ulimit name>=<soft limit>:<hard limit>", for example:
# "nofile=1024:2048"
# If nothing is set here, settings will be inherited from the CRI-O daemon
# default_ulimits = [
# ]

# If true, the runtime will not use pivot_root, but instead use MS_MOVE.
# no_pivot = false

# decryption_keys_path is the path where the keys required for
# image decryption are stored. This option supports live configuration reload.
# decryption_keys_path = "/etc/crio/keys/"

# Path to the conmon binary, used for monitoring the OCI runtime.
# Will be searched for using $PATH if empty.
# This option is currently deprecated, and will be replaced with RuntimeHandler.MonitorEnv.
# conmon = ""

# Cgroup setting for conmon
# This option is currently deprecated, and will be replaced with RuntimeHandler.MonitorCgroup.
# conmon_cgroup = ""

# Environment variable list for the conmon process, used for passing necessary
# environment variables to conmon or the runtime.
# This option is currently deprecated, and will be replaced with RuntimeHandler.MonitorEnv.
# conmon_env = [
# ]

# Additional environment variables to set for all the
# containers. These are overridden if set in the
# container image spec or in the container runtime configuration.
# default_env = [
# ]

# If true, SELinux will be used for pod separation on the host.
selinux = true

# Path to the seccomp.json profile which is used as the default seccomp profile
# for the runtime. If not specified, then the internal default seccomp profile
# will be used. This option supports live configuration reload.
# seccomp_profile = ""

# Changes the meaning of an empty seccomp profile. By default
# (and according to CRI spec), an empty profile means unconfined.
# This option tells CRI-O to treat an empty profile as the default profile,
# which might increase security.
# This option is currently deprecated,
# and will be replaced by the SeccompDefault FeatureGate in Kubernetes.
# seccomp_use_default_when_empty = true

# Used to change the name of the default AppArmor profile of CRI-O. The default
# profile name is "crio-default". This profile only takes effect if the user
# does not specify a profile via the Kubernetes Pod's metadata annotation. If
# the profile is set to "unconfined", then this equals to disabling AppArmor.
# This option supports live configuration reload.
# apparmor_profile = "crio-default"

# Path to the blockio class configuration file for configuring
# the cgroup blockio controller.
# blockio_config_file = ""

# Used to change irqbalance service config file path which is used for configuring
# irqbalance daemon.
# irqbalance_config_file = "/etc/sysconfig/irqbalance"

# irqbalance_config_restore_file allows to set a cpu mask CRI-O should
# restore as irqbalance config at startup. Set to empty string to disable this flow entirely.
# By default, CRI-O manages the irqbalance configuration to enable dynamic IRQ pinning.
# irqbalance_config_restore_file = "/etc/sysconfig/orig_irq_banned_cpus"

# Path to the RDT configuration file for configuring the resctrl pseudo-filesystem.
# This option supports live configuration reload.
# rdt_config_file = ""

# Cgroup management implementation used for the runtime.
cgroup_manager = "systemd"

# Specify whether the image pull must be performed in a separate cgroup.
# separate_pull_cgroup = ""

# List of default capabilities for containers. If it is empty or commented out,
# only the capabilities defined in the containers json file by the user/kube
# will be added.
# default_capabilities = [
# 	"CHOWN",
# 	"DAC_OVERRIDE",
# 	"FSETID",
# 	"FOWNER",
# 	"SETGID",
# 	"SETUID",
# 	"SETPCAP",
# 	"NET_BIND_SERVICE",
# 	"KILL",
# ]

# Add capabilities to the inheritable set, as well as the default group of permitted, bounding and effective.
# If capabilities are expected to work for non-root users, this option should be set.
# add_inheritable_capabilities = false

# List of default sysctls. If it is empty or commented out, only the sysctls
# defined in the container json file by the user/kube will be added.
# default_sysctls = [
# ]

# List of devices on the host that a
# user can specify with the "io.kubernetes.cri-o.Devices" allowed annotation.
# allowed_devices = [
# 	"/dev/fuse",
# ]

# List of additional devices. specified as
# "<device-on-host>:<device-on-container>:<permissions>", for example: "--device=/dev/sdc:/dev/xvdc:rwm".
# If it is empty or commented out, only the devices
# defined in the container json file by the user/kube will be added.
# additional_devices = [
# ]

# List of directories to scan for CDI Spec files.
# cdi_spec_dirs = [
# 	"/etc/cdi",
# 	"/var/run/cdi",
# ]

# Change the default behavior of setting container devices uid/gid from CRI's
# SecurityContext (RunAsUser/RunAsGroup) instead of taking host's uid/gid.
# Defaults to false.
# device_ownership_from_security_context = false

# Path to OCI hooks directories for automatically executed hooks. If one of the
# directories does not exist, then CRI-O will automatically skip them.
# hooks_dir = [
# 	"/usr/share/containers/oci/hooks.d",
# ]

# Path to the file specifying the defaults mounts for each container. The
# format of the config is /SRC:/DST, one mount per line. Notice that CRI-O reads
# its default mounts from the following two files:
#
#   1) /etc/containers/mounts.conf (i.e., default_mounts_file): This is the
#      override file, where users can either add in their own default mounts, or
#      override the default mounts shipped with the package.
#
#   2) /usr/share/containers/mounts.conf: This is the default file read for
#      mounts. If you want CRI-O to read from a different, specific mounts file,
#      you can change the default_mounts_file. Note, if this is done, CRI-O will
#      only add mounts it finds in this file.
#
# default_mounts_file = ""

# Maximum number of processes allowed in a container.
# This option is deprecated. The Kubelet flag '--pod-pids-limit' should be used instead.
# pids_limit = 0

# Maximum sized allowed for the container log file. Negative numbers indicate
# that no size limit is imposed. If it is positive, it must be >= 8192 to
# match/exceed conmon's read buffer. The file is truncated and re-opened so the
# limit is never exceeded. This option is deprecated. The Kubelet flag '--container-log-max-size' should be used instead.
# log_size_max = -1

# Whether container output should be logged to journald in addition to the kubernetes log file
# log_to_journald = false

# Path to directory in which container exit files are written to by conmon.
# container_exits_dir = "/var/run/crio/exits"

# Path to directory for container attach sockets.
# container_attach_socket_dir = "/var/run/crio"

# The prefix to use for the source of the bind mounts.
# bind_mount_prefix = ""

# If set to true, all containers will run in read-only mode.
# read_only = false

# Changes the verbosity of the logs based on the level it is set to. Options
# are fatal, panic, error, warn, info, debug and trace. This option supports
# live configuration reload.
# log_level = "info"

# Filter the log messages by the provided regular expression.
# This option supports live configuration reload.
# log_filter = ""

# The UID mappings for the user namespace of each container. A range is
# specified in the form containerUID:HostUID:Size. Multiple ranges must be
# separated by comma.
# uid_mappings = ""

# The GID mappings for the user namespace of each container. A range is
# specified in the form containerGID:HostGID:Size. Multiple ranges must be
# separated by comma.
# gid_mappings = ""

# If set, CRI-O will reject any attempt to map host UIDs below this value
# into user namespaces.  A negative value indicates that no minimum is set,
# so specifying mappings will only be allowed for pods that run as UID 0.
# minimum_mappable_uid = -1

# If set, CRI-O will reject any attempt to map host GIDs below this value
# into user namespaces.  A negative value indicates that no minimum is set,
# so specifying mappings will only be allowed for pods that run as UID 0.
# minimum_mappable_gid = -1

# The minimal amount of time in seconds to wait before issuing a timeout
# regarding the proper termination of the container. The lowest possible
# value is 30s, whereas lower values are not considered by CRI-O.
# ctr_stop_timeout = 30

# drop_infra_ctr determines whether CRI-O drops the infra container
# when a pod does not have a private PID namespace, and does not use
# a kernel separating runtime (like kata).
# It requires manage_ns_lifecycle to be true.
# drop_infra_ctr = true

# infra_ctr_cpuset determines what CPUs will be used to run infra containers.
# You can use linux CPU list format to specify desired CPUs.
# To get better isolation for guaranteed pods, set this parameter to be equal to kubelet reserved-cpus.
# infra_ctr_cpuset = ""

# The directory where the state of the managed namespaces gets tracked.
# Only used when manage_ns_lifecycle is true.
# namespaces_dir = "/var/run"

# pinns_path is the path to find the pinns binary, which is needed to manage namespace lifecycle
# pinns_path = ""

# Globally enable/disable CRIU support which is necessary to
# checkpoint and restore container or pods (even if CRIU is found in $PATH).
# enable_criu_support = false

# Enable/disable the generation of the container,
# sandbox lifecycle events to be sent to the Kubelet to optimize the PLEG
# enable_pod_events = false

# default_runtime is the _name_ of the OCI runtime to be used as the default.
# default_runtime is the _name_ of the OCI runtime to be used as the default.
# The name is matched against the runtimes map below.
# default_runtime = "runc"

# A list of paths that, when absent from the host,
# will cause a container creation to fail (as opposed to the current behavior being created as a directory).
# This option is to protect from source locations whose existence as a directory could jeopardize the health of the node, and whose
# creation as a file is not desired either.
# An example is /etc/hostname, which will cause failures on reboot if it's created as a directory, but often doesn't exist because
# the hostname is being managed dynamically.
# absent_mount_sources_to_reject = [
# ]

# The "crio.runtime.runtimes" table defines a list of OCI compatible runtimes.
# The runtime to use is picked based on the runtime handler provided by the CRI.
# If no runtime handler is provided, the "default_runtime" will be used.
# Each entry in the table should follow the format:
#
# [crio.runtime.runtimes.runtime-handler]
# runtime_path = "/path/to/the/executable"
# runtime_type = "oci"
# runtime_root = "/path/to/the/root"
# monitor_path = "/path/to/container/monitor"
# monitor_cgroup = "/cgroup/path"
# monitor_exec_cgroup = "/cgroup/path"
# monitor_env = []
# privileged_without_host_devices = false
# allowed_annotations = []
# platform_runtime_paths = { "os/arch" = "/path/to/binary" }
# Where:
# - runtime-handler: Name used to identify the runtime.
# - runtime_path (optional, string): Absolute path to the runtime executable in
#   the host filesystem. If omitted, the runtime-handler identifier should match
#   the runtime executable name, and the runtime executable should be placed
#   in $PATH.
# - runtime_type (optional, string): Type of runtime, one of: "oci", "vm". If
#   omitted, an "oci" runtime is assumed.
# - runtime_root (optional, string): Root directory for storage of containers
#   state.
# - runtime_config_path (optional, string): the path for the runtime configuration
#   file. This can only be used with when using the VM runtime_type.
# - privileged_without_host_devices (optional, bool): an option for restricting
#   host devices from being passed to privileged containers.
# - allowed_annotations (optional, array of strings): an option for specifying
#   a list of experimental annotations that this runtime handler is allowed to process.
#   The currently recognized values are:
#   "io.kubernetes.cri-o.userns-mode" for configuring a user namespace for the pod.
#   "io.kubernetes.cri-o.cgroup2-mount-hierarchy-rw" for mounting cgroups writably when set to "true".
#   "io.kubernetes.cri-o.Devices" for configuring devices for the pod.
#   "io.kubernetes.cri-o.ShmSize" for configuring the size of /dev/shm.
#   "io.kubernetes.cri-o.UnifiedCgroup.$CTR_NAME" for configuring the cgroup v2 unified block for a container.
#   "io.containers.trace-syscall" for tracing syscalls via the OCI seccomp BPF hook.
#   "io.kubernetes.cri.rdt-class" for setting the RDT class of a container
# - monitor_path (optional, string): The path of the monitor binary. Replaces
#   deprecated option "conmon".
# - monitor_cgroup (optional, string): The cgroup the container monitor process will be put in.
#   Replaces deprecated option "conmon_cgroup".
# - monitor_exec_cgroup (optional, string): If set to "container", indicates exec probes
#   should be moved to the container's cgroup
# - monitor_env (optional, array of strings): Environment variables to pass to the montior.
#   Replaces deprecated option "conmon_env".
# - platform_runtime_paths (optional, map): A mapping of platforms to the corresponding
#   runtime executable paths for the runtime handler.
#
# Using the seccomp notifier feature:
#
# This feature can help you to debug seccomp related issues, for example if
# blocked syscalls (permission denied errors) have negative impact on the workload.
#
# To be able to use this feature, configure a runtime which has the annotation
# "io.kubernetes.cri-o.seccompNotifierAction" in the allowed_annotations array.
#
# It also requires at least runc 1.1.0 or crun 0.19 which support the notifier
# feature.
#
# If everything is setup, CRI-O will modify chosen seccomp profiles for
# containers if the annotation "io.kubernetes.cri-o.seccompNotifierAction" is
# set on the Pod sandbox. CRI-O will then get notified if a container is using
# a blocked syscall and then terminate the workload after a timeout of 5
# seconds if the value of "io.kubernetes.cri-o.seccompNotifierAction=stop".
#
# This also means that multiple syscalls can be captured during that period,
# while the timeout will get reset once a new syscall has been discovered.
#
# This also means that the Pods "restartPolicy" has to be set to "Never",
# otherwise the kubelet will restart the container immediately.
#
# Please be aware that CRI-O is not able to get notified if a syscall gets
# blocked based on the seccomp defaultAction, which is a general runtime
# limitation.


# [crio.runtime.runtimes.runc]
# runtime_path = ""
# runtime_type = "oci"
# runtime_root = "/run/runc"
# runtime_config_path = ""
# monitor_path = ""
# monitor_cgroup = "system.slice"
# monitor_exec_cgroup = ""
# monitor_env = [
# 	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
# ]
# allowed_annotations = [
# 	"io.containers.trace-syscall",
# ]
# privileged_without_host_devices = false


# The workloads table defines ways to customize containers with different resources
# that work based on annotations, rather than the CRI.
# Note, the behavior of this table is EXPERIMENTAL and may change at any time.
# Each workload, has a name, activation_annotation, annotation_prefix and set of resources it supports mutating.
# The currently supported resources are "cpu" (to configure the cpu shares) and "cpuset" to configure the cpuset.
# Each resource can have a default value specified, or be empty.
# For a container to opt-into this workload, the pod should be configured with the annotation $activation_annotation (key only, value is ignored).
# To customize per-container, an annotation of the form $annotation_prefix.$resource/$ctrName = "value" can be specified
# signifying for that resource type to override the default value.
# If the annotation_prefix is not present, every container in the pod will be given the default values.
# Example:
# [crio.runtime.workloads.workload-type]
# activation_annotation = "io.crio/workload"
# annotation_prefix = "io.crio.workload-type"
# [crio.runtime.workloads.workload-type.resources]
# cpuset = 0
# cpushares = "0-1"
# Where:
# The workload name is workload-type.
# To specify, the pod must have the "io.crio.workload" annotation (this is a precise string match).
# This workload supports setting cpuset and cpu resources.
# annotation_prefix is used to customize the different resources.
# To configure the cpu shares a container gets in the example above, the pod would have to have the following annotation:
# "io.crio.workload-type/$container_name = {"cpushares": "value"}"

# hostnetwork_disable_selinux determines whether
# SELinux should be disabled within a pod when it is running in the host network namespace
# Default value is set to true
# hostnetwork_disable_selinux = true

# disable_hostport_mapping determines whether to enable/disable
# the container hostport mapping in CRI-O.
# Default value is set to 'false'
# disable_hostport_mapping = false

# The crio.image table contains settings pertaining to the management of OCI images.
#
# CRI-O reads its configured registries defaults from the system wide
# containers-registries.conf(5) located in /etc/containers/registries.conf. If
# you want to modify just CRI-O, you can change the registries configuration in
# this file. Otherwise, leave insecure_registries and registries commented out to
# use the system's defaults from /etc/containers/registries.conf.
[crio.image]

# Default transport for pulling images from a remote container storage.
# default_transport = "docker://"

# The path to a file containing credentials necessary for pulling images from
# secure registries. The file is similar to that of /var/lib/kubelet/config.json
# global_auth_file = ""

# The image used to instantiate infra containers.
# This option supports live configuration reload.
# pause_image = "registry.k8s.io/pause:3.9"

# The path to a file containing credentials specific for pulling the pause_image from
# above. The file is similar to that of /var/lib/kubelet/config.json
# This option supports live configuration reload.
# pause_image_auth_file = ""

# The command to run to have a container stay in the paused state.
# When explicitly set to "", it will fallback to the entrypoint and command
# specified in the pause image. When commented out, it will fallback to the
# default: "/pause". This option supports live configuration reload.
# pause_command = "/pause"

# List of images to be excluded from the kubelet's garbage collection.
# It allows specifying image names using either exact, glob, or keyword
# patterns. Exact matches must match the entire name, glob matches can
# have a wildcard * at the end, and keyword matches can have wildcards
# on both ends. By default, this list includes the "pause" image if
# configured by the user, which is used as a placeholder in Kubernetes pods.
# pinned_images = [
# ]

# Path to the file which decides what sort of policy we use when deciding
# whether or not to trust an image that we've pulled. It is not recommended that
# this option be used, as the default behavior of using the system-wide default
# policy (i.e., /etc/containers/policy.json) is most often preferred. Please
# refer to containers-policy.json(5) for more details.
# signature_policy = ""

# Root path for pod namespace-separated signature policies.
# The final policy to be used on image pull will be <SIGNATURE_POLICY_DIR>/<NAMESPACE>.json.
# If no pod namespace is being provided on image pull (via the sandbox config),
# or the concatenated path is non existent, then the signature_policy or system
# wide policy will be used as fallback. Must be an absolute path.
# signature_policy_dir = "/etc/crio/policies"

# List of registries to skip TLS verification for pulling images. Please
# consider configuring the registries via /etc/containers/registries.conf before
# changing them here.
# insecure_registries = [
# ]

# Controls how image volumes are handled. The valid values are mkdir, bind and
# ignore; the latter will ignore volumes entirely.
# image_volumes = "mkdir"

# Temporary directory to use for storing big files
# big_files_temporary_dir = ""

# The crio.network table containers settings pertaining to the management of
# CNI plugins.
[crio.network]

# The default CNI network name to be selected. If not set or "", then
# CRI-O will pick-up the first one found in network_dir.
# cni_default_network = ""

# Path to the directory where CNI configuration files are located.
network_dir = "/etc/cni/net.d/"

# Paths to directories where CNI plugin binaries are located.
plugin_dirs = [
	"/opt/cni/bin",
	"/usr/libexec/cni",
]

# A necessary configuration for Prometheus based metrics retrieval
[crio.metrics]

# Globally enable or disable metrics support.
enable_metrics = true

# Specify enabled metrics collectors.
# Per default all metrics are enabled.
# It is possible, to prefix the metrics with "container_runtime_" and "crio_".
# For example, the metrics collector "operations" would be treated in the same
# way as "crio_operations" and "container_runtime_crio_operations".
# metrics_collectors = [
# 	"operations",
# 	"operations_latency_microseconds_total",
# 	"operations_latency_microseconds",
# 	"operations_errors",
# 	"image_pulls_by_digest",
# 	"image_pulls_by_name",
# 	"image_pulls_by_name_skipped",
# 	"image_pulls_failures",
# 	"image_pulls_successes",
# 	"image_pulls_layer_size",
# 	"image_layer_reuse",
# 	"containers_events_dropped_total",
# 	"containers_oom_total",
# 	"containers_oom",
# 	"processes_defunct",
# 	"operations_total",
# 	"operations_latency_seconds",
# 	"operations_latency_seconds_total",
# 	"operations_errors_total",
# 	"image_pulls_bytes_total",
# 	"image_pulls_skipped_bytes_total",
# 	"image_pulls_failure_total",
# 	"image_pulls_success_total",
# 	"image_layer_reuse_total",
# 	"containers_oom_count_total",
# 	"containers_seccomp_notifier_count_total",
# 	"resources_stalled_at_stage",
# ]
# The port on which the metrics server will listen.
metrics_port = 9537

# Local socket path to bind the metrics server to
# metrics_socket = ""

# The certificate for the secure metrics server.
# If the certificate is not available on disk, then CRI-O will generate a
# self-signed one. CRI-O also watches for changes of this path and reloads the
# certificate on any modification event.
# metrics_cert = ""

# The certificate key for the secure metrics server.
# Behaves in the same way as the metrics_cert.
# metrics_key = ""

# A necessary configuration for OpenTelemetry trace data exporting
[crio.tracing]

# Globally enable or disable exporting OpenTelemetry traces.
# enable_tracing = false

# Address on which the gRPC trace collector listens on.
# tracing_endpoint = "0.0.0.0:4317"

# Number of samples to collect per million spans. Set to 1000000 to always sample.
# tracing_sampling_rate_per_million = 0

# CRI-O NRI configuration.
[crio.nri]

# Globally enable or disable NRI.
# enable_nri = false

# NRI socket to listen on.
# nri_listen = "/var/run/nri/nri.sock"

# NRI plugin directory to use.
# nri_plugin_dir = "/opt/nri/plugins"

# NRI plugin configuration directory to use.
# nri_plugin_config_dir = "/etc/nri/conf.d"

# Disable connections from externally launched NRI plugins.
# nri_disable_connections = false

# Timeout for a plugin to register itself with NRI.
# nri_plugin_registration_timeout = "5s"

# Timeout for a plugin to handle an NRI request.
# nri_plugin_request_timeout = "2s"

# Necessary information pertaining to container and pod stats reporting.
[crio.stats]

# The number of seconds between collecting pod and container stats.
# If set to 0, the stats are collected on-demand instead.
# stats_collection_period = 0

Maheshvara@RegalFoyer:~$

**Comment by thedarkone-maheshwara** [comment]
any follow ups please help
