### ISSUE TITLE
PGP key expired

### ISSUE THREAD

**Issue by pavel-jancik** [cri-o/cri-o#6432]
### What happened?

I was trying to install the cri-o on the Ubuntu following the docs steps in https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems

But I was not getting errors on `apt-get update`

```
Err:7 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
Err:8 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
Err:9 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/xUbuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
Reading package lists... Done
```

The apt sources looks like:
```sh
$ cat '/etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.20.list'
deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04/ /

$ cat '/etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.21.list'
deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/xUbuntu_20.04/ /

$ cat '/etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list'
deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /

$ ls -la /usr/share/keyrings/libcontainers-*
-rw-r--r-- 1 root root 723 Dec  6 14:16 /usr/share/keyrings/libcontainers-archive-keyring.gpg
-rw-r--r-- 1 root root 723 Dec  6 14:16 /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
```

Also note that if I run `apt-key list` I get that PGP key is exprired (today).
```
$ curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key             | sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg       add -

$ apt-key list
...
/etc/apt/trusted.gpg.d/libcontainers.gpg
----------------------------------------
pub   rsa2048 2018-08-03 [SC] [expired: 2022-12-06]
      2472 D6D0 D2F6 6AF8 7ABA  8DA3 4D64 3903 7506 0AA4
uid           [ expired] devel:kubic OBS Project <devel:kubic@build.opensuse.org>

```

### What did you expect to happen?

The PGP key is updated so that it is possible to install cri-o on ubuntu from official repo.

### How can we reproduce it (as minimally and precisely as possible)?

```sh
 set -x \ 
 && OS=xUbuntu_20.04 \
 && VERSION=1.21 \
 && { cat <<EOF | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /
EOF
} \
 && { cat <<EOF | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /
EOF
} \
 && sudo apt-get install -y curl gpg \
 && sudo mkdir -p /usr/share/keyrings \
 && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | sudo  gpg --dearmor --no-tty  -o /usr/share/keyrings/libcontainers-archive-keyring.gpg \
 && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | sudo gpg --dearmor --no-tty -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg \
 && sudo apt-get update
```

### Anything else we need to know?

Probably hits also Debian users.

### CRI-O and Kubernetes version

Not applicable cri-o installation fails.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux  some-hostname 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Ubuntu VM
</details>

**Comment by D1StrX** [comment]
![image](https://user-images.githubusercontent.com/40062371/205942499-4b28e216-76ec-4f58-8b14-eafa2d7539ba.png)
I also walked into the exact same problem. 
Another thing, since apt-key is deprecated.
For debian it would be /etc/apt/trusted.gpg.d:
```
OS=_<xUbuntu_22.04>_
VERSION=_<1.25>_
curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/libcontainers-archive-keyring.gpg
curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/libcontainers-crio-archive-keyring.gpg
echo "deb [signed-by=/etc/apt/trusted.gpg.d/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb [signed-by=/etc/apt/trusted.gpg.d/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" | sudo tee "/etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list"
sudo apt update
```

**Comment by camaeel** [comment]
As a solution for the future there might be some automation (even a GH workflow executed weekly) to check if the key is valid at least next 10-14 days

**Comment by kthguru** [comment]
It's a blocking issue to us. Is there any update? Thank you.

**Comment by pavel-jancik** [comment]
@haircommander: Sorry for tagging, but could you please do a brief look on this issue.

**Comment by Yessoami** [comment]
I have also same problem! Is there any solution so far?
Anybody knows alternative solution to solve this problem? It would be also good to let me know a treaky solution.

**Comment by pczerkas** [comment]
Solution for Ubuntu:

<pre>
export OS=xUbuntu_20.04
export CRIO_VERSION=1.25
export CRIO_PATCH_VERSION=0
export CRIO_REVISION=0

echo "deb [ allow-insecure=yes ] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /"| sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:$OS.list
echo "deb [ allow-insecure=yes ] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o/$OS/ /"| sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$OS.list
echo "deb [ allow-insecure=yes ] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION:/$CRIO_VERSION.$CRIO_PATCH_VERSION/$OS/ /"| sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.$CRIO_PATCH_VERSION.list

#curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION:/$CRIO_VERSION.$CRIO_PATCH_VERSION/$OS/Release.key | sudo apt-key add -
#curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/Release.key | sudo apt-key add -
#curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | sudo apt-key add -

# Allow unauthenticated packages
cat > /etc/apt/apt.conf.d/99allow_unauth << EOF      <<<<<<<<<<< remove space between "<<" and "EOF" (couldn't post this line exactly here)
APT { Get { AllowUnauthenticated "1"; }; };
EOF

apt-get --allow-unauthenticated update
apt-get --allow-unauthenticated install -y cri-o=$CRIO_VERSION.$CRIO_PATCH_VERSION~$CRIO_REVISION cri-o-runc
</pre>

**Comment by kthguru** [comment]
Is this a dead project? Is there any person in responsible for this issue? We are using 22.04.01 LTS and cri-o v1.25.1. Please help us.

**Comment by piengeng** [comment]
just wondering if this is related 

https://kubic.opensuse.org/blog/2022-06-10-kubic-retired/
https://lists.opensuse.org/archives/list/kubic@lists.opensuse.org/thread/23ODJTP4PLGC3HWFQNA2MD4ETFSNW4KV/

**Comment by D1StrX** [comment]
@saschagrunert or @cblecker could someone of the Maintainers give an update on this issue?

**Comment by jefflill** [comment]
I played around with the workaround suggested by @pczerkas and came up with a somewhat easier temporary workaround.  The idea is to add **trusted=yes** to the **deb ...** lines appended to the repo lists, like:
```
echo ""deb [trusted=yes signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /"" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
```
Note that if more than one optional property (like shown above) you'll need to space separate these within the **[ ... ]** section.

**Comment by haircommander** [comment]
xref https://github.com/openSUSE/open-build-service/issues/13493

I [commented](https://build.opensuse.org/project/show/devel:kubic) on the top level of `devel:kubic`, someone who has more power than I have needs to extend the key.

**Comment by haircommander** [comment]
Alright, the packages are at the point where I can rebuild them and the issue goes away. I've done 1.25 already, and will go down to 1.21 (as that's the lowest I've seen here). let me know if you need something earlier, or if I missed any

**Comment by haircommander** [comment]
Should be all fixed now, can folks confirm so we can close this?

**Comment by D1StrX** [comment]
Just tried it, added crio download repo fresh. Apt update works for 1.25.x
![image](https://user-images.githubusercontent.com/40062371/206556274-8f1295f4-7439-4296-951c-29893436981d.png)
Not sure if the unknown is correct though.

**Comment by jefflill** [comment]
Yeah, it looks like this got fixed upstream: https://github.com/openSUSE/open-build-service/issues/13493

**Comment by AndrewSav** [comment]
@jefflill no, it was not fixed upstream, it was closed, with a notice that it was a wrong place to file the issue, but yes, it seems working now.

**Comment by anxolerd** [comment]
Still having an issue when trying to install an older version of CRI-O according to the installation guide:

```root@REDACTED:~# export OS=xUbuntu_18.04
root@REDACTED:~# export VERSION=1.19
root@REDACTED:~# curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | gpg -v
gpg: WARNING: unsafe ownership on homedir '/home/REDACTED/.gnupg'
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1093  100  1093    0     0   8036      0 --:--:-- --:--:-- --:--:--  8036
gpg: armor header: Version: GnuPG v1.4.5 (GNU/Linux)
pub   rsa2048 2018-08-03 [SC] [expired: 2022-12-06]
      2472D6D0D2F66AF87ABA8DA34D64390375060AA4
uid           devel:kubic OBS Project <devel:kubic@build.opensuse.org>
sig        4D64390375060AA4 2020-09-27   [selfsig]
sig        3B3011B76B9D6523 2018-08-03   [User ID not found]
root@REDACTED:~# curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg -v
gpg: WARNING: unsafe ownership on homedir '/home/REDACTED/.gnupg'
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1093  100  1093    0     0   5605      0 --:--:-- --:--:-- --:--:--  5605
gpg: armor header: Version: GnuPG v1.4.5 (GNU/Linux)
pub   rsa2048 2018-08-03 [SC] [expires: 2025-02-14]
      2472D6D0D2F66AF87ABA8DA34D64390375060AA4
uid           devel:kubic OBS Project <devel:kubic@build.opensuse.org>
sig        4D64390375060AA4 2022-12-07   [selfsig]
sig        3B3011B76B9D6523 2018-08-03   [User ID not found]
root@REDACTED:~#```

**Comment by haircommander** [comment]
I only updated the supported releases; any reason why you are still using 1.19?
