### ISSUE TITLE
CRI-O 1.26 / 1.27 panics while starting containers in user namespace on Kubernetes 1.27

### ISSUE THREAD

**Issue by Syquel** [cri-o/cri-o#6833]
### What happened?

If Kubernetes 1.27 tries to start a pod with `hostUsers: false` containers should be started in a user namespace.  

Starting these containers results in the following panic in CRI-O 1.26 and 1.27:
```
crio[2286]: time="2023-04-20 11:34:35.054129181+02:00" level=info msg="Creating container: aquasecurity/trivy-operator-6fcd987f96-vcl9t/trivy-operator" id=09dd0bd5-f359-420c-af2f-d4cd9679c49b name=/runtime.v1.RuntimeService/CreateContainer
crio[2286]: time="2023-04-20 11:34:35.054470669+02:00" level=warning msg="Allowed annotations are specified for workload [io.containers.trace-syscall]"
crio[2286]: panic: runtime error: index out of range [0] with length 0
crio[2286]: goroutine 290 [running]:
crio[2286]: panic({0x560488f072c0, 0xc000acc438})
crio[2286]:         /usr/lib/go/src/runtime/panic.go:987 +0x3bb fp=0xc0011d3b88 sp=0xc0011d3ac8 pc=0x5604870d871b
crio[2286]: runtime.goPanicIndex(0x0, 0x0)
crio[2286]:         /usr/lib/go/src/runtime/panic.go:113 +0x7f fp=0xc0011d3bc8 sp=0xc0011d3b88 pc=0x5604870d66df
crio[2286]: github.com/cri-o/cri-o/server.getOCIMappings(...)
crio[2286]:         /build/cri-o/src/cri-o-1.27.0/server/container_create_linux.go:1083
crio[2286]: github.com/cri-o/cri-o/server.addOCIBindMounts({0x5604890468c8?, 0xc00118fa10?}, {0x56048905d040, 0xc001192480}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, ...}, ...)
crio[2286]:         /build/cri-o/src/cri-o-1.27.0/server/container_create_linux.go:1053 +0x1d10 fp=0xc0011d4198 sp=0xc0011d3bc8 pc=0x56048866a990
crio[2286]: github.com/cri-o/cri-o/server.(*Server).createSandboxContainer(0xc0000af500, {0x5604890468c8?, 0xc00118f4a0?}, {0x56048905d040, 0xc001192480}, 0xc000253500)
crio[2286]:         /build/cri-o/src/cri-o-1.27.0/server/container_create_linux.go:326 +0x1625 fp=0xc0011d5640 sp=0xc0011d4198 pc=0x5604886614c5
crio[2286]: github.com/cri-o/cri-o/server.(*Server).CreateContainer(0xc0000af500, {0x5604890468c8, 0xc00118f4a0}, 0xc00118e810)
crio[2286]:         /build/cri-o/src/cri-o-1.27.0/server/container_create.go:417 +0xe7c fp=0xc0011d58f8 sp=0xc0011d5640 pc=0x56048865db5c
crio[2286]: k8s.io/cri-api/pkg/apis/runtime/v1._RuntimeService_CreateContainer_Handler.func1({0x5604890468c8, 0xc00118f4a0}, {0x560488f848c0?, 0xc00118e810})
crio[2286]:         /build/cri-o/src/pkg/mod/k8s.io/kubernetes/staging/src/k8s.io/cri-api@v0.0.0-20230411170423-1b4df30b3cdf/pkg/apis/runtime/v1/api.pb.go:10845 +0x78 fp=0xc0011d5938 sp=0xc0011d58f8 pc=0x560487c9edd8
crio[2286]: github.com/cri-o/cri-o/server/otel-collector.UnaryInterceptor.func1({0x5604890468c8, 0xc00118e7e0}, {0x560488f848c0, 0xc00118e810}, 0xc000a8c580, 0xc000946150)
crio[2286]:         /build/cri-o/src/cri-o-1.27.0/server/otel-collector/interceptors.go:64 +0x1a6 fp=0xc0011d5a10 sp=0xc0011d5938 pc=0x5604886ae0a6
crio[2286]: k8s.io/cri-api/pkg/apis/runtime/v1._RuntimeService_CreateContainer_Handler({0x56048901cdc0?, 0xc0000af500}, {0x5604890468c8, 0xc00118e7e0}, 0xc0003720e0, 0x560489021ac8)
crio[2286]:         /build/cri-o/src/pkg/mod/k8s.io/kubernetes/staging/src/k8s.io/cri-api@v0.0.0-20230411170423-1b4df30b3cdf/pkg/apis/runtime/v1/api.pb.go:10847 +0x138 fp=0xc0011d5a68 sp=0xc0011d5a10 pc=0x560487c9ec98
crio[2286]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000036000, {0x56048904f798, 0xc000e54000}, 0xc000993680, 0xc000891dd0, 0x560489ec23b0, 0x0)
crio[2286]:         /build/cri-o/src/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3 fp=0xc0011d5e48 sp=0xc0011d5a68 pc=0x560487c64533
crio[2286]: google.golang.org/grpc.(*Server).handleStream(0xc000036000, {0x56048904f798, 0xc000e54000}, 0xc000993680, 0x0)
crio[2286]:         /build/cri-o/src/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36 fp=0xc0011d5f68 sp=0xc0011d5e48 pc=0x560487c69656
crio[2286]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
crio[2286]:         /build/cri-o/src/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x98 fp=0xc0011d5fe0 sp=0xc0011d5f68 pc=0x560487c61e58
crio[2286]: runtime.goexit()
[...]
```
(truncated because of GitHub character limit)

### What did you expect to happen?

The container should be successfully started in a user namespace without panicking.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a Pod with `hostUsers: false` on Kubernetes 1.27 with CRI-O 1.26 / 1.27.

### Anything else we need to know?

Downgrading Kubelet to 1.26.3 solves this issue.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.0
Version:        1.27.0
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-04-19T12:36:23Z
GoVersion:      go1.20.3
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  containers_image_ostree_stub
  apparmor
  seccomp
LDFlags:           -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=2023-04-19T12:36:23Z -compressdwarf=false -linkmode external
SeccompEnabled:   true
AppArmorEnabled:  true
```

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"archive", BuildDate:"2023-04-15T11:34:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
$ uname -a
Linux syquel.de 6.2.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 13 Apr 2023 16:59:24 +0000 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
thanks for opening an issue! this should be fixed here https://github.com/cri-o/cri-o/pull/6834 are you able to verify it fixes your issue?

**Comment by Syquel** [comment]
I made a new build from your branch, but it still panics.

Log:
```
crio[2405]: time="2023-04-22 13:49:39.513087516+02:00" level=info msg="Creating container: aquasecurity/trivy-operator-7677bf58ff-n6f7d/trivy-operator" id=fa8a1b2e-ff05-4940-b0ca-2de46b21c4bc name=/runtime.v1.RuntimeService/CreateContainer
crio[2405]: time="2023-04-22 13:49:39.513435297+02:00" level=warning msg="Allowed annotations are specified for workload [io.containers.trace-syscall]"
crio[2405]: panic: runtime error: index out of range [0] with length 0
crio[2405]: goroutine 238 [running]:
crio[2405]: panic({0x55d45e0a9c80, 0xc00100cd68})
crio[2405]:         /usr/lib/go/src/runtime/panic.go:987 +0x3bb fp=0xc000f83b88 sp=0xc000f83ac8 pc=0x55d45c28a6db
crio[2405]: runtime.goPanicIndex(0x0, 0x0)
crio[2405]:         /usr/lib/go/src/runtime/panic.go:113 +0x7f fp=0xc000f83bc8 sp=0xc000f83b88 pc=0x55d45c28869f
crio[2405]: github.com/cri-o/cri-o/server.getOCIMappings(...)
crio[2405]:         /home/builder/cri-o/src/cri-o-1.27.1/server/container_create_linux.go:1083
crio[2405]: github.com/cri-o/cri-o/server.addOCIBindMounts({0x55d45e1e9288?, 0xc000838ea0?}, {0x55d45e1ffa00, 0xc00081a4e0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, ...}, ...)
crio[2405]:         /home/builder/cri-o/src/cri-o-1.27.1/server/container_create_linux.go:1053 +0x1d10 fp=0xc000f84198 sp=0xc000f83bc8 pc=0x55d45d81c950
crio[2405]: github.com/cri-o/cri-o/server.(*Server).createSandboxContainer(0xc000285100, {0x55d45e1e9288?, 0xc0008388d0?}, {0x55d45e1ffa00, 0xc00081a4e0}, 0xc000039500)
crio[2405]:         /home/builder/cri-o/src/cri-o-1.27.1/server/container_create_linux.go:326 +0x1625 fp=0xc000f85640 sp=0xc000f84198 pc=0x55d45d813485
crio[2405]: github.com/cri-o/cri-o/server.(*Server).CreateContainer(0xc000285100, {0x55d45e1e9288, 0xc0008388d0}, 0xc0002ef740)
crio[2405]:         /home/builder/cri-o/src/cri-o-1.27.1/server/container_create.go:417 +0xe7c fp=0xc000f858f8 sp=0xc000f85640 pc=0x55d45d80fb1c
crio[2405]: k8s.io/cri-api/pkg/apis/runtime/v1._RuntimeService_CreateContainer_Handler.func1({0x55d45e1e9288, 0xc0008388d0}, {0x55d45e127280?, 0xc0002ef740})
crio[2405]:         /home/builder/cri-o/src/pkg/mod/k8s.io/kubernetes/staging/src/k8s.io/cri-api@v0.0.0-20230411170423-1b4df30b3cdf/pkg/apis/runtime/v1/api.pb.go:10845 +0x78 fp=0xc000f85938 sp=0xc000f858f8 pc=0x55d45ce50d98
crio[2405]: github.com/cri-o/cri-o/server/otel-collector.UnaryInterceptor.func1({0x55d45e1e9288, 0xc0002ef710}, {0x55d45e127280, 0xc0002ef740}, 0xc0005e57e0, 0xc0011a7500)
crio[2405]:         /home/builder/cri-o/src/cri-o-1.27.1/server/otel-collector/interceptors.go:64 +0x1a6 fp=0xc000f85a10 sp=0xc000f85938 pc=0x55d45d860066
crio[2405]: k8s.io/cri-api/pkg/apis/runtime/v1._RuntimeService_CreateContainer_Handler({0x55d45e1bf780?, 0xc000285100}, {0x55d45e1e9288, 0xc0002ef710}, 0xc00077f730, 0x55d45e1c4488)
crio[2405]:         /home/builder/cri-o/src/pkg/mod/k8s.io/kubernetes/staging/src/k8s.io/cri-api@v0.0.0-20230411170423-1b4df30b3cdf/pkg/apis/runtime/v1/api.pb.go:10847 +0x138 fp=0xc000f85a68 sp=0xc000f85a10 pc=0x55d45ce50c58
crio[2405]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002fc5a0, {0x55d45e1f2158, 0xc000748d00}, 0xc000c1c480, 0xc0007cb350, 0x55d45f0693b0, 0x0)
crio[2405]:         /home/builder/cri-o/src/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3 fp=0xc000f85e48 sp=0xc000f85a68 pc=0x55d45ce164f3
crio[2405]: google.golang.org/grpc.(*Server).handleStream(0xc0002fc5a0, {0x55d45e1f2158, 0xc000748d00}, 0xc000c1c480, 0x0)
crio[2405]:         /home/builder/cri-o/src/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36 fp=0xc000f85f68 sp=0xc000f85e48 pc=0x55d45ce1b616
crio[2405]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
crio[2405]:         /home/builder/cri-o/src/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x98 fp=0xc000f85fe0 sp=0xc000f85f68 pc=0x55d45ce13e18
crio[2405]: runtime.goexit()
```

**Comment by Syquel** [comment]
I added a log statement just before the loop in line 1082 to get get some further insight.  
```
time="2023-04-22 20:56:40.992062603+02:00" level=info msg="len(m): 1 | len(ids): 0" id=6067ef78-8638-4c3a-8cc3-9c8a564e0d15 name=/runtime.v1.RuntimeService/CreateContainer
```

I don't know much about Go, but the `ids` array is apparently created with a capacitiy of `len(m)` and length `0`.  
Because the length is `0` and we try to access the array via index it panics.   

I guess `append()` should be used instead of indexed-based access?

**Comment by Syquel** [comment]
Reopen this issue, please.

As stated above the bug has not been fixed.

**Comment by Syquel** [comment]
@haircommander shall I open a new issue for the error where conmon fails?  
It works with kubelet 1.26 so I guess this is still an issue with cri-o and not with conmon itself.

**Comment by haircommander** [comment]
I think it's actually an issue with the runtime. which are you using: crun or runc?

**Comment by Syquel** [comment]
crun.  

I could try to get a debug log tomorrow, but otherwise I don't know how to pinpoint that error.

**Comment by haircommander** [comment]
cc @giuseppe @flouthoc

**Comment by giuseppe** [comment]
the error happens because we are trying to use idmapped mounts with a tmpfs.  Support for idmapped mounts for tmpfs were added to Linux 6.3.  You'll need to update the kernel

**Comment by Syquel** [comment]
# Linux Kernel 6.2.13
Just verified this on Linux kernel 6.2.13 with the following reproducer:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: reproducer-crio-userns
spec:
  hostUsers: false
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: "RuntimeDefault"
  containers:
    - name: userns-mount-test
      image: "registry.fedoraproject.org/fedora:38"
      command: [ "/bin/bash", "-c" ]
      args:
        - |
          while true; do
            date
            sleep 5s
          done
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: "/mnt/sample"
          name: sample-mnt
  volumes:
    - name: sample-mnt
      emptyDir:
        medium: "Memory"
```
* Setting `.spec.volumes[0].emptyDir.medium` to "" (empty string / local fs bind mount) successfully starts the container
* Setting `.spec.volumes[0].emptyDir.medium` to "Memory" (tmpfs mount) makes the container crash on startup
* Setting `.spec.automountServiceAccountToken` to `true` (tmpfs mount) makes the container crash on startup

When I switch from `crun` to `runc` the container does not start even with `.spec.volumes[0].emptyDir.medium` set to "" and `.spec.automountServiceAccountToken` set to `true` (even though it started with these settings with crun):
```
crio[533]: time="2023-04-30 12:26:19.153887227+02:00" level=info msg="Creating container: default/reproducer-crio-userns/userns-mount-test" id=08407268-a69e-425f-aaf2-bac6d0c431ef name=/runtime.v1.RuntimeService/CreateContainer
crio[533]: time="2023-04-30 12:26:19.154208050+02:00" level=warning msg="Allowed annotations are specified for workload [io.containers.trace-syscall]"
crio[533]: time="2023-04-30 12:26:19.175098441+02:00" level=info msg="Container \"99990b39d0c71f9ede7fa51602cb9d6eaf1f18c672ebd75ff3d6fcc37b321e16\" is a besteffort pod. Skip PreStart." id=08407268-a69e-425f-aaf2-bac6d0c431ef name=/runtime.v1.RuntimeService/CreateContainer
systemd[1]: Started crio-conmon-99990b39d0c71f9ede7fa51602cb9d6eaf1f18c672ebd75ff3d6fcc37b321e16.scope.
systemd[1]: Started libcontainer container 99990b39d0c71f9ede7fa51602cb9d6eaf1f18c672ebd75ff3d6fcc37b321e16.
systemd[1]: crio-99990b39d0c71f9ede7fa51602cb9d6eaf1f18c672ebd75ff3d6fcc37b321e16.scope: Deactivated successfully.
conmon[13389]: conmon 99990b39d0c71f9ede7f <nwarn>: runtime stderr: time="2023-04-30T12:26:19+02:00" level=error msg="runc create failed: unable to start container process: error during container init: error mounting \"/run/containers/storage/overlay-containers/91133ee0ac797ccc79b6c7ae9145a96154fc001022e6fc7b43f21297d40dc523/userdata/hostname\" to rootfs at \"/etc/hostname\": mount /proc/self/fd/8:/etc/hostname (via /proc/self/fd/14), flags: 0x1021: operation not permitted"
conmon[13389]: conmon 99990b39d0c71f9ede7f <error>: Failed to create container: exit status 1
crio[533]: time="2023-04-30 12:26:19.391433630+02:00" level=error msg="Container creation error: time=\"2023-04-30T12:26:19+02:00\" level=error msg=\"runc create failed: unable to start container process: error during container init: error mounting \\\"/run/containers/storage/overlay-containers/91133ee0ac797ccc79b6c7ae9145a96154fc001022e6fc7b43f21297d40dc523/userdata/hostname\\\" to rootfs at \\\"/etc/hostname\\\": mount /proc/self/fd/8:/etc/hostname (via /proc/self/fd/14), flags: 0x1021: operation not permitted\"\n" id=08407268-a69e-425f-aaf2-bac6d0c431ef name=/runtime.v1.RuntimeService/CreateContainer
```

Setting `.spec.hostUsers` to `true` (and therefore disabling user namespaces) the pod starts successfully with crun as well as runc.
Downgrading kubelet from 1.27 to 1.26 and keeping user namespaces enabled via `hostUsers: false` fixes the issue, too.

I am not sure if these are separate issues for crun and runc or if the issue is in cri-o.

# Linux Kernel 6.3.0
I upgraded to Linux kernel 6.3.0 and tested the same Pod configuration from above with kubelet 1.27, `.spec.hostUsers: false`, `.spec.automountServiceAccountToken: true` and `.spec.volumes[0].emptyDir.medium: "Memory"` and everything works fine so far.  
So it really seems to be an issue with idmapped tmpfs mounts on Linux kernel <6.3.  
It is just weird to me that it works with kubelet 1.26 but not 1.27.
